### ISSUE TITLE
git reset --hard  ${GST_PLUGIN_VAAPI_REPO_DISPLAY_LOCK_PATCH_HASH} failed

### ISSUE THREAD

**Issue by aiopeniot** [opencv/gst-video-analytics#10]
build with dockerfile, can't pass the step:

ARG GST_PLUGIN_VAAPI_REPO_DISPLAY_LOCK_PATCH_HASH=b219f6095f3014041896714dd88e7d90ee3d72dd
git clone https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi.git -b 1.14 --depth 10
 git reset --hard ${GST_PLUGIN_VAAPI_REPO_DISPLAY_LOCK_PATCH_HASH}

failed: fatal b219f6095f3014041896714dd88e7d90ee3d72dd

**Comment by mshabunin** [comment]
You need more than 10 commits on branch 1.14, try to change shallow clone depth to `--depth 50`.

**Comment by Andruxin52rus** [comment]
@mshabunin thank you for help with this one! @aiopeniot we needed a particular commit with our fix of gstreamer-vaapi in R1 release. Now it's included into common gstreamer-vaapi 1.16 distribution and we got rid of these lines in our Dockerfile. You're welcome to check out our latest R1.2 release
