### ISSUE TITLE
WARNING: erroneous pipeline: no property "converter" in element "gvametaconvert0"

### ISSUE THREAD

**Issue by MauryaShraddha** [opencv/gst-video-analytics#102]
Hello,

I am trying to publish the results of a pipeline through mqtt using the gvtametapublish. Following is the pipeline I am trying to execute:

`export OUTFILE=/opt/intel/openvino_2020.3.194/output/`

`gst-launch-1.0 urisourcebin buffer-size=4096 uri=https://github.com/intel-iot-devkit/sample-videos/raw/master/head-pose-face-detection-female-and-male.mp4 ! decodebin ! videoconvert ! video/x-raw,format=BGRx ! gvadetect model=/root/intel/dl_streamer/models/intel/face-detection-adas-0001/FP32/face-detection-adas-0001.xml device=CPU ! queue ! gvaclassify model=/root/intel/dl_streamer/models/intel/age-gender-recognition-retail-0013/FP32/age-gender-recognition-retail-0013.xml model-proc=/opt/intel/openvino/data_processing/dl_streamer/samples/gst_launch/face_detection_and_classification/model_proc/age-gender-recognition-retail-0013.json device=CPU ! queue ! gvaclassify model=/root/intel/dl_streamer/models/intel/emotions-recognition-retail-0003/FP32/emotions-recognition-retail-0003.xml model-proc=/opt/intel/openvino/data_processing/dl_streamer/samples/gst_launch/face_detection_and_classification/model_proc/emotions-recognition-retail-0003.json device=CPU ! queue ! gvaclassify model=/root/intel/dl_streamer/models/intel/landmarks-regression-retail-0009/FP32/landmarks-regression-retail-0009.xml model-proc=/opt/intel/openvino/data_processing/dl_streamer/samples/gst_launch/face_detection_and_classification/model_proc/landmarks-regression-retail-0009.json device=CPU ! queue ! gvawatermark ! videoconvert ! fpsdisplaysink video-sink=ximagesink sync=false ! gvametaconvert converter=json method=all ! gvametapublish method=file filepath=${OUTFILE} outputformat=stream  ! fakesink`

I get the following error:
`WARNING: erroneous pipeline: no property "converter" in element "gvametaconvert0"`

I am trying this on Docker in Windows10 OS as described at https://github.com/opencv/gst-video-analytics/issues/75

@nnshah1 Can you please guide me on this?

Thank you

**Comment by adranit** [comment]
Hi @MauryaShraddha,

You should change a name of this property to "format". 
Please visit https://github.com/opencv/gst-video-analytics/wiki/gvametaconvert for details.

Thanks,
Anton

**Comment by MauryaShraddha** [comment]
@adranit Thank you. That solution worked. I modified the pipeline solving the errors I was getting. However, I am a newbie in writing the pipeline and mqtt. Following is the pipeline I wrote until now:

`gst-launch-1.0 urisourcebin buffer-size=4096 uri=https://github.com/intel-iot-devkit/sample-videos/raw/master/head-pose-face-detection-female-and-male.mp4 ! decodebin ! videoconvert ! video/x-raw,format=BGRx ! gvadetect model=/root/intel/dl_streamer/models/intel/face-detection-adas-0001/FP32/face-detection-adas-0001.xml device=CPU ! queue ! gvaclassify model=/root/intel/dl_streamer/models/intel/age-gender-recognition-retail-0013/FP32/age-gender-recognition-retail-0013.xml model-proc=/opt/intel/openvino/data_processing/dl_streamer/samples/gst_launch/face_detection_and_classification/model_proc/age-gender-recognition-retail-0013.json device=CPU ! queue ! gvaclassify model=/root/intel/dl_streamer/models/intel/emotions-recognition-retail-0003/FP32/emotions-recognition-retail-0003.xml model-proc=/opt/intel/openvino/data_processing/dl_streamer/samples/gst_launch/face_detection_and_classification/model_proc/emotions-recognition-retail-0003.json device=CPU ! queue ! gvaclassify model=/root/intel/dl_streamer/models/intel/landmarks-regression-retail-0009/FP32/landmarks-regression-retail-0009.xml model-proc=/opt/intel/openvino/data_processing/dl_streamer/samples/gst_launch/face_detection_and_classification/model_proc/landmarks-regression-retail-0009.json device=CPU ! queue ! gvawatermark ! videoconvert ! fpsdisplaysink video-sink=ximagesink sync=false ! gvametaconvert format=json ! gvametapublish method=mqtt ! fakesink`

I am getting the following error:
`WARNING: erroneous pipeline: could not link fpsdisplaysink0 to gvametaconvert0`

Can you please guide me on how can I publish the results of this pipeline through mqtt? How can I use the "mqtt-client-id" property of the gvametapublish?

Thank you

**Comment by adranit** [comment]
Hi @MauryaShraddha,
The fpsdisplaysink element must be put in the end of pipeline due to it does not have a src pad. The same rules cover the fakesink element - it must be the last element. 
Try the following:
... sion-retail-0009.json device=CPU ! queue ! gvametaconvert format=json ! gvametapublish method=mqtt ! fakesink

Also you can use the [metapublish ](https://github.com/opencv/gst-video-analytics/tree/master/samples/gst_launch/metapublish) sample for reference.

Anton

**Comment by MauryaShraddha** [comment]
Thank you @adranit. I will give this a try. How can I get the metapublish sample and the metapublish.sh in my OpenVINO environment in Docker?

**Comment by adranit** [comment]
@MauryaShraddha , I would recommend you to use OV2020.4 because of metapublish sample was not included in OV2020.3.  Otherwise you can download this sample from GitHub and pass it to Docker image.

**Comment by MauryaShraddha** [comment]
Hi @adranit 

Glad to inform you that the change you suggested in the pipeline worked. There are no errors now. However, can you help me understand how to interpret the output? Below is the screenshot of the output I got:

![image](https://user-images.githubusercontent.com/36510998/90836700-150e3c80-e31e-11ea-8fb8-51488a2da841.png)

![image](https://user-images.githubusercontent.com/36510998/90836715-20616800-e31e-11ea-8093-dba467966c83.png)

Thank you

**Comment by MauryaShraddha** [comment]
Hi @adranit 

I also tried the metapublish sample. I tried to execute the following:
`./metapublish.sh https://github.com/intel-iot-devkit/sample-videos/raw/master/head-pose-face-detection-female-and-male.mp4 mqtt`

I get the following:
`MODEL2: age-gender-recognition-retail-0013
MODEL2_PROC: ./model_proc/age-gender-recognition-retail-0013.json
urisourcebin buffer-size=4096 uri=https://github.com/intel-iot-devkit/sample-videos/raw/master/head-pose-face-detection-female-and-male.mp4
gst-launch-1.0 urisourcebin buffer-size=4096 uri=https://github.com/intel-iot-devkit/sample-videos/raw/master/head-pose-face-detection-female-and-male.mp4 ! decodebin ! gvadetect model=/root/intel/dl_streamer/models/intel/face-detection-adas-0001/FP32/face-detection-adas-0001.xml device=CPU ! queue ! gvaclassify model=/root/intel/dl_streamer/models/intel/age-gender-recognition-retail-0013/FP32/age-gender-recognition-retail-0013.xml model-proc=./model_proc/age-gender-recognition-retail-0013.json device=CPU ! queue ! gvametaconvert format =json ! gvametapublish method=mqtt address=localhost:1883 topic=dlstreamer ! fakesink sync=false
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Got context from element 'source': gst.soup.session=context, session=(SoupSession)NULL, force=(boolean)false;
Redistribute latency...
ERROR: from element /GstPipeline:pipeline0/GstGvaClassify:gvaclassify0: base_inference plugin intitialization failed
Additional debug info:
/root/gst-video-analytics/gst/inference_elements/base/inference_singleton.cpp(118): acquire_inference_instance (): /GstPipeline:pipeline0/GstGvaClassify:gvaclassify0:
Not able to parse model-proc file './model_proc/age-gender-recognition-retail-0013.json'
 model-proc validation failed
  At /input_preproc/0 of {"format":"image","layer_name":"data"} - required property 'color_format' not found in object
ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
Freeing pipeline ...`

Following is the screenshot of the same:
![image](https://user-images.githubusercontent.com/36510998/90838485-01190980-e323-11ea-874b-7238bc0d8690.png)

Can you please guide on how we can resolve this?

**Comment by adranit** [comment]
Hi @MauryaShraddha,
I guess you are using the sample from 2020.4 with OV2020.3. Am I right?
If so, I would recommend to change the model_proc file ./model_proc/age-gender-recognition-retail-0013.json by https://github.com/opencv/gst-video-analytics/blob/v1.0.1/samples/model_proc/age-gender-recognition-retail-0013.json.  

Anton

**Comment by MauryaShraddha** [comment]
Hi @adranit , 

I updated my openvino image in docker recently. I am getting some other issue regarding downloading the models. 
Here is the issue: https://github.com/opencv/gst-video-analytics/issues/104

Thank you

**Comment by MauryaShraddha** [comment]
Hi @adranit 

It worked. I updated the openvino image and resolved the #104 issue too. I am getting no errors now. 
I just wanted to know how can I use the "mqtt-client-id" property of the gvametapublish in the pipeline. 
So far I am running this: 
`./metapublish.sh https://github.com/intel-iot-devkit/sample-videos/raw/master/head-pose-face-detection-female-and-male.mp4 mqtt`
After the last part, that is, mqtt, I want to mention the mqtt-client-id. Is it the same as the mqtt topic name? How do we specify this in the above pipeline?

Thank you

**Comment by MauryaShraddha** [comment]
Hello,

I got the output. First I executed the following command on terminal 1:
`./metapublish.sh https://github.com/intel-iot-devkit/sample-videos/raw/master/head-pose-face-detection-female-and-male.mp4 mqtt`
On another terminal I executed the following command:
`mosquitto_sub -h localhost -t dlstreamer`

I referred this from: https://docs.openvinotoolkit.org/latest/gst_samples_gst_launch_metapublish_listener.html

Thank you for the guidance @adranit
