### ISSUE TITLE
What is difference between tracking-type short-term and zero-term?

### ISSUE THREAD

**Issue by chungyehwangai** [opencv/gst-video-analytics#103]
What is difference between tracking-type short-term and zero-term? 

https://github.com/opencv/gst-video-analytics/blob/preview/audio-detect/samples/gst_launch/vehicle_pedestrian_tracking/vehicle_pedestrian_tracking.sh

uses short-term and 10 as detection interval. Could i use smaller or larger interval? What interval should i use when using zero-term interval?

Thanks

**Comment by brmarkus** [comment]
Under "https://github.com/opencv/gst-video-analytics/wiki/gvatrack" it says:

```
tracking-type       : Tracking algorithm used to identify the same object in multiple frames. Please see user guide for more details
                        flags: readable, writable
                        Enum "GstGvaTrackingType" Default: 0, "short-term"
                           (0): short-term       - Short-term tracker
                           (1): zero-term        - Zero-term tracker
```
Under "https://software.intel.com/content/www/us/en/develop/articles/openvino-relnotes.html" it says:


`gvatrack | To perform object tracking using zero-term or short-term tracking algorithms. Zero-term tracking assigns unique object IDs and requires object detection to run on every frame. Short-term tracking allows to track objects between frames, thereby reducing the need to run object detection on each frame.`

In OpenCV, it is used loke this:
* zero-term tracking: every frame
* short-term tracking: <30 frames
* long-term tracking: >30 frames

**Comment by chungyehwangai** [comment]
@brmarkus  Thanks for the information!
