### ISSUE TITLE
Can't run face_detection_and_classification shell example

### ISSUE THREAD

**Issue by martinangel** [opencv/gst-video-analytics#11]
Hello, 

I'm trying to run the face_detection_and_classification shell example in Ubuntu 16.04

As recommended, I have followed instructions [how to build plugins and run samples in docker container](https://github.com/opencv/gst-video-analytics/wiki/Build-docker-image-from-sources-and-run-docker-container).

In the step related to datasets and models I found "ready-for-use models in IR (Intermediate Representation, .xml + .bin) format" [here](https://download.01.org/opencv/2019/open_model_zoo/R1/models_bin/). These models are in IR (_XML+BIN_) format and you have the _FP32_ folder that the code of _./face_detection_and_classification.sh_ is looking for.

I have also downloaded the videos from [here](https://github.com/intel-iot-devkit/sample-videos)

Then, I have followed your instructions to run samples from [here](https://github.com/opencv/gst-video-analytics/wiki/Build-and-Run) and [here](https://github.com/opencv/gst-video-analytics/tree/master/samples/shell)

Then I have executed:

`GST_DEBUG=2 ./face_detection_and_classification.sh /root/video-examples/face-demographics-walking.mp4`

However, I get the same error than [here](https://github.com/opencv/open_model_zoo/issues/67)

```
GST_PLUGIN_PATH=/usr/lib/va-gstreamer-plugins/
LD_LIBRARY_PATH=/usr/local/lib/:/usr/lib/va-gstreamer-plugins/:/usr/lib/x86_64-linux-gnu/:/opt/intel/dldt/inference-engine/lib/ubuntu_16.04/:/opt/intel/dldt/inference-engine/lib/ubuntu_16.04/intel64/:/opt/intel/dldt/inference-engine/external/omp/lib/:/opt/intel/dldt/inference-engine/lib/
Setting pipeline to PAUSED ...
0:00:00.077278574  1666      0x1eb8e90 WARN                xcontext xvcontext.c:534:gst_xvcontext_check_xshm_calls: MIT-SHM extension check failed at XShmAttach. Not using shared memory.
0:00:00.130583818  1666      0x1eb8e90 WARN                 default inference.cpp:310:Inference:<gvainference0> Loading model: device=CPU, path=/root/intel_models/intel/FP32/face-detection-adas-0001.xml
0:00:00.130604465  1666      0x1eb8e90 WARN                 default inference.cpp:311:Inference:<gvainference0> Setting batch_size=1, nireq=2
0:00:00.211738817  1666      0x1eb8e90 WARN            gvainference gstgvainference.c:452:gst_gva_inference_start:<gvainference0> error: gvainference plugin intitialization failed
0:00:00.211770068  1666      0x1eb8e90 WARN            gvainference gstgvainference.c:452:gst_gva_inference_start:<gvainference0> error: Incorrect number of input edges for layer mbox_conf_reshape
/opt/intel/dldt/inference-engine/include/details/ie_exception_conversion.hpp:71
0:00:00.211814134  1666      0x1eb8e90 WARN                GST_PADS gstpad.c:1149:gst_pad_set_active:<gvainference0:sink> Failed to activate pad
ERROR: Pipeline doesn't want to pause.
ERROR: from element /GstPipeline:pipeline0/GstGvaInference:gvainference0: gvainference plugin intitialization failed
Additional debug info:
/root/gstreamer-plugins/gst/elements/gvainference/gstgvainference.c(452): gst_gva_inference_start (): /GstPipeline:pipeline0/GstGvaInference:gvainference0:
Incorrect number of input edges for layer mbox_conf_reshape
/opt/intel/dldt/inference-engine/include/details/ie_exception_conversion.hpp:71
Setting pipeline to NULL ...
Freeing pipeline ...
```

As you can see there is a problem about _MKLDNNPlugin_ with an **Incorrect number of input edges for layer mbox_conf_reshape**

It looks like a model format problem of openVINO...

Could you explicitly point out the URL from where to download the models or the specific version to be employed?

Thank you.

**Comment by umed** [comment]
Hi @martinangel ,

Probably, your problem is related to OpenVINO. I think you have downloaded not appropriate models for your OpenVINO version.

OpenVINO versions 2018 R5 and 2019 R1 support slightly different format of IR optimized models.

Our current master and latest release support only **OpenVINO 2018 R5** and you can download appropriate models by using appropriate version of [model downloader (2018 R5)](https://github.com/opencv/open_model_zoo/tree/2018_R5/model_downloader).

Thanks for reporting this issue. We will address this on our wiki..

**Comment by Andruxin52rus** [comment]
Hi @martinangel ! We've released R1.2 lately along with significantly improved documentation: https://github.com/opencv/gst-video-analytics/wiki/Getting-Started-Guide-%5BR1.2%5D. It was tested by a couple of QA engineers and confirmed that samples run successfully. Please install GVA plugin from scratch and check if that works for you. If it doesn't, please reopen the issue
