### ISSUE TITLE
Missing "vehicle_and_pedestrian_classification_videomemory.sh " shell script sample

### ISSUE THREAD

**Issue by Mushtaq-BGA** [opencv/gst-video-analytics#15]
"vehicle_and_pedestrian_classification_videomemory.sh ", i see this in Readme but couldn't find this shell script in samples/shell folder. please  can you add this sample.

**Comment by umed** [comment]
Hi @Mushtaq-BGA ,

That shell script is not applicable anymore. Currently, we support only custom allocators.

If you would like to pass video memory through pipeline you can:

1. Implement custom allocator that wraps your video memory buffer
2. Register it in gstreamer
3. Specify name of your allocator in pipeline via property `allocator-name`

More details regarding GstAllocator you can find [here](https://gstreamer.freedesktop.org/documentation/gstreamer/gstallocator.html)
