### ISSUE TITLE
Device Support

### ISSUE THREAD

**Issue by sonal1905** [opencv/gst-video-analytics#17]
How can we run the application on GPU?

**Comment by Andruxin52rus** [comment]
Hi @sonal1905 ! If you want inference on GPU, you can select it with GVA elements' `device` property, for instance: `gvadetect device=GPU`. Please see example of pipeline with detection running on GPU here: https://github.com/opencv/gst-video-analytics/blob/master/samples/shell/console_measure_fps_gpu.sh.
