### ISSUE TITLE
running models with openVino R1

### ISSUE THREAD

**Issue by sonal1905** [opencv/gst-video-analytics#18]
"gvaclassify plugin intitialization failed" error on running with Openvino R1

**Comment by Andruxin52rus** [comment]
Hi @sonal1905 ! We need more details on the issue. First of all, what release of GVA plugin do you try to use? If it's latest master (or tag v0.4, or R1.2), it must be used with OpenVINO R1.1 (you can find this information in Getting Started Guide for chosen [release R1.2](https://github.com/opencv/gst-video-analytics/releases/tag/v0.4)). We do not guarantee backward compatibility with older OpenVINO versions

**Comment by sonal1905** [comment]
Hi @Andruxin52rus ! I am able to solve the error. Thanks for your time.
Need help on another issue:
Can we pass the classification model (**gvaclassify**) without the detection model (**gvadetect**). I am trying to classify fruit model.

**Comment by Andruxin52rus** [comment]
Hi @sonal1905 ! Currently `gvaclassify` relies on detections generated by `gvadetect`, or more generally - on `GstVideoRegionOfInterestMeta` instances attached to currently passing through pipeline `GstBuffer` instance. Hence it is not possible to use  `gvaclassify` without `gvadetect` or other sources of `GstVideoRegionOfInterestMeta` instances.
For your case I recommend to use `gvadetect` with general-purpose object detection model (like ssd300, mobilenet-ssd). See [here](https://github.com/opencv/gst-video-analytics/wiki/Getting-Started-Guide-%5BR1.2%5D#5-advanced-usage-) for steps to obtain such models.
When you have one of these detection models, you can do following:
```
gst-launch-1.0 ... ! gvadetect model=ssd300 ! gvaclassify ...
```
If it doesn't help, please reopen the issue
