### ISSUE TITLE
Build failed on ubuntu 16.04

### ISSUE THREAD

**Issue by burialpine** [opencv/gst-video-analytics#2]
OS: Ubuntu 16.04
Steps:
sudo apt-get install libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools

sudo apt-get install libgstreamer-plugins-base1.0-dev

source /opt/intel/computer_vision_sdk/bin/setupvars.sh
export MODELS_PATH=/opt/intel/computer_vision_sdk/deployment_tools/intel_models

git clone https://github.com/opencv/gst-video-analytics.git
cd ~/gst-video-analytics
mkdir build
cd build
cmake ..
make -j8

Error Message
[ 60%] Building CXX object gst/common/CMakeFiles/common.dir/meta_converters.cpp.o
In file included from /media/ylin8/work/gst-video-analytics/gst/common/meta_converters.cpp:8:0:
/media/ylin8/work/gst-video-analytics/gst-libs/gst/videoanalytics/gva_roi_meta.h: In function ‘GstMeta* _gst_buffer_iterate_meta_filtered(GstBuffer*, void**, GType)’:
/media/ylin8/work/gst-video-analytics/gst-libs/gst/videoanalytics/gva_roi_meta.h:36:64: error: suggest parentheses around assignment used as truth value [-Werror=parentheses]
     while (meta = gst_buffer_iterate_meta(gst_buffer, state_ptr))
                                                                ^
In file included from /media/ylin8/work/gst-video-analytics/gst/common/meta_converters.cpp:8:0:
/media/ylin8/work/gst-video-analytics/gst-libs/gst/videoanalytics/gva_roi_meta.h: In constructor ‘GVA::RegionOfInterest::RegionOfInterest(GstVideoRegionOfInterestMeta*)’:
/media/ylin8/work/gst-video-analytics/gst-libs/gst/videoanalytics/gva_roi_meta.h:186:45: error: ‘struct GstVideoRegionOfInterestMeta’ has no member named ‘params’
         tensors.reserve(g_list_length(meta->params));
                                             ^
/media/ylin8/work/gst-video-analytics/gst-libs/gst/videoanalytics/gva_roi_meta.h:188:31: error: ‘struct GstVideoRegionOfInterestMeta’ has no member named ‘params’
         for (GList *l = meta->params; l; l = g_list_next(l)) {
                               ^
/media/ylin8/work/gst-video-analytics/gst/common/meta_converters.cpp: In function ‘bool Attributes2Text(GstStructure*)’:
/media/ylin8/work/gst-video-analytics/gst/common/meta_converters.cpp:42:54: error: ‘gst_structure_get_array’ was not declared in this scope
     if (!gst_structure_get_array(s, "labels", &labels))
                                                      ^
In file included from /media/ylin8/work/gst-video-analytics/gst/common/blob2metadata.cpp:8:0:
/media/ylin8/work/gst-video-analytics/gst-libs/gst/videoanalytics/gva_roi_meta.h: In function ‘GstMeta* _gst_buffer_iterate_meta_filtered(GstBuffer*, void**, GType)’:
/media/ylin8/work/gst-video-analytics/gst-libs/gst/videoanalytics/gva_roi_meta.h:36:64: error: suggest parentheses around assignment used as truth value [-Werror=parentheses]
     while (meta = gst_buffer_iterate_meta(gst_buffer, state_ptr))
                                                                ^
/media/ylin8/work/gst-video-analytics/gst-libs/gst/videoanalytics/gva_roi_meta.h: In constructor ‘GVA::RegionOfInterest::RegionOfInterest(GstVideoRegionOfInterestMeta*)’:
/media/ylin8/work/gst-video-analytics/gst-libs/gst/videoanalytics/gva_roi_meta.h:186:45: error: ‘struct GstVideoRegionOfInterestMeta’ has no member named ‘params’
         tensors.reserve(g_list_length(meta->params));
                                             ^
/media/ylin8/work/gst-video-analytics/gst-libs/gst/videoanalytics/gva_roi_meta.h:188:31: error: ‘struct GstVideoRegionOfInterestMeta’ has no member named ‘params’
         for (GList *l = meta->params; l; l = g_list_next(l)) {
                               ^
cc1plus: all warnings being treated as errors
gst/common/CMakeFiles/common.dir/build.make:158: recipe for target 'gst/common/CMakeFiles/common.dir/meta_converters.cpp.o' failed
make[2]: *** [gst/common/CMakeFiles/common.dir/meta_converters.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/media/ylin8/work/gst-video-analytics/gst/common/blob2metadata.cpp: In function ‘void Blob2RoiMeta(const std::map<std::__cxx11::basic_string<char>, std::shared_ptr<InferenceBackend::OutputBlob> >&, std::vector<InferenceFrame>, const gchar*, const gchar*, const std::map<std::__cxx11::basic_string<char>, _GstStructure*>&)’:
/media/ylin8/work/gst-video-analytics/gst/common/blob2metadata.cpp:123:64: error: ‘gst_video_region_of_interest_meta_add_param’ was not declared in this scope
             gst_video_region_of_interest_meta_add_param(meta, s);
                                                                ^
cc1plus: all warnings being treated as errors
gst/common/CMakeFiles/common.dir/build.make:86: recipe for target 'gst/common/CMakeFiles/common.dir/blob2metadata.cpp.o' failed
make[2]: *** [gst/common/CMakeFiles/common.dir/blob2metadata.cpp.o] Error 1
CMakeFiles/Makefile2:113: recipe for target 'gst/common/CMakeFiles/common.dir/all' failed
make[1]: *** [gst/common/CMakeFiles/common.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mikhail-nikolskiy** [comment]
Plugins require GStreamer version >= 1.14 because use [field 'params' in struct GstVideoRegionOfInterestMeta](https://github.com/GStreamer/gst-plugins-base/blob/master/gst-libs/gst/video/gstvideometa.h#L300) introduced in GStreamer 1.14.
On Ubuntu 16.04 the easiest way is to build and run [docker container](https://github.com/opencv/gst-video-analytics/wiki/Build-docker-image-from-sources-and-run-docker-container) with all dependencies including GStreamer.
On Ubuntu 18.04 the apt-get installs GStreamer version 1.14 compatible with plugins.

**Comment by burialpine** [comment]
hi, thanks, with docker image,  i have successfully launched the sample.

**Comment by mikhail-nikolskiy** [comment]
Update on this question.
We will try to improve compatibility with GStreamer version less than 1.14 for elements gvainference and gvadetect on one of next updates.
The field 'params' in struct GstVideoRegionOfInterestMeta only used in gvaclassify element.
