### ISSUE TITLE
Build fails on enabling the VA-API in the latest docker.

### ISSUE THREAD

**Issue by vijnasu** [opencv/gst-video-analytics#21]
/root/gstreamer-plugins/inference_backend/pre_proc/vaapi/vaapi_pre_proc.cpp: In function 'VASurfaceID InferenceBackend::CreateVASurfaceFromAlignedBuffer(VADisplay, InferenceBackend::Image&)':
/root/gstreamer-plugins/inference_backend/pre_proc/vaapi/vaapi_pre_proc.cpp:140:23: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
     for (int i = 0; i < external.num_planes; i++) {
                       ^
/root/gstreamer-plugins/inference_backend/pre_proc/vaapi/vaapi_pre_proc.cpp: In member function 'virtual void InferenceBackend::VAAPIPreProc::ReleaseImage(const InferenceBackend::Image&)':
/root/gstreamer-plugins/inference_backend/pre_proc/vaapi/vaapi_pre_proc.cpp:202:20: error: statement has no effect [-Werror=unused-value]
         image.type == MemoryType::ANY;
                    ^
/root/gstreamer-plugins/inference_backend/pre_proc/vaapi/vaapi_pre_proc.cpp: At global scope:
/root/gstreamer-plugins/inference_backend/pre_proc/vaapi/vaapi_pre_proc.cpp:126:20: error: 'VASurfaceID InferenceBackend::CreateVASurfaceFromAlignedBuffer(VADisplay, InferenceBackend::Image&)' defined but not used [-Werror=unused-function]
 static VASurfaceID CreateVASurfaceFromAlignedBuffer(VADisplay dpy, Image &src) {
                    ^
cc1plus: all warnings being treated as errors
make[2]: *** [inference_backend/pre_proc/vaapi/CMakeFiles/vaapi_pre_proc.dir/vaapi_pre_proc.cpp.o] Error 1
inference_backend/pre_proc/vaapi/CMakeFiles/vaapi_pre_proc.dir/build.make:62: recipe for target 'inference_backend/pre_proc/vaapi/CMakeFiles/vaapi_pre_proc.dir/vaapi_pre_proc.cpp.o' failed
CMakeFiles/Makefile2:1058: recipe for target 'inference_backend/pre_proc/vaapi/CMakeFiles/vaapi_pre_proc.dir/all' failed
make[1]: *** [inference_backend/pre_proc/vaapi/CMakeFiles/vaapi_pre_proc.dir/all] Error 2

**Comment by umed** [comment]
Hi @vijnasu ,

it's experimental and it is under `ifdef`. We know about problem. This problem will be fixed in future release.
