### ISSUE TITLE
Build fails on enabling "tests building" in latest docker

### ISSUE THREAD

**Issue by vijnasu** [opencv/gst-video-analytics#22]
CMake Error at thirdparty/CMakeLists.txt:12 (add_subdirectory):
  The source directory

    /root/gstreamer-plugins/thirdparty/googletest

  does not contain a CMakeLists.txt file.

-- Found OpenCV: /usr/local (found version "4.1.0") found components:  core imgproc
-- Checking for module 'gstreamer-check-1.0'
--   Found gstreamer-check-1.0, version 1.16.0
-- Found OpenCV: /usr/local (found version "4.1.0") found components:  core imgproc imgcodecs
-- Configuring incomplete, errors occurred!
See also "/root/gstreamer-plugins/build/CMakeFiles/CMakeOutput.log".
See also "/root/gstreamer-plugins/build/CMakeFiles/CMakeError.log".
The command '/bin/sh -c mkdir -p gstreamer-plugins/build         && cd gstreamer-plugins/build         && cmake         -DCMAKE_INSTALL_PREFIX=/usr ..         -DVERSION_PATCH=${SOURCE_REV}         -DGIT_INFO=${GIT_INFO}         -DBUILD_SHARED_LIBS=ON         -DENABLE_PAHO_INSTALLATION=${ENABLE_PAHO_INSTALLATION}         -DENABLE_RDKAFKA_INSTALLATION=${ENABLE_RDKAFKA_INSTALLATION}         -DCMAKE_INSTALL_PREFIX=/usr ..         && make -j $(nproc)         && make install         && echo "/usr/lib/va-gstreamer-plugins" >> /etc/ld.so.conf.d/opencv-dldt-gst.conf && ldconfig' returned a non-zero code: 1

**Comment by umed** [comment]
Hi @vijnasu,

Can you recheck? Don't see line from the error. There could be mistake during uploading release, but seems that CMakeLists.txt should be fine right now.

**Comment by umed** [comment]
@vijnasu , cannot reproduce and no answers.  Feel free to reopen.
