### ISSUE TITLE
remove file-existing test in metapublish file writer

### ISSUE THREAD

**Issue by xwu2git** [opencv/gst-video-analytics#23]
This test is not useful and prevents the option of passing interference results to fifo.

**Comment by tobiasmo1** [comment]
Would overwriting or appending to the file be suitable for outputformat="batch" or is your issue limited to outputformat="stream" configuration?

This file existence test avoids introducing data destructive behavior by default; and encourages creation of unique output filenames by callers at the time a pipeline is initiated.

We conceive that an appropriate naming convention for inference files avoids such naming collisions by including creation timestamp, sequence ### if file exists, and likely contains contextual information such as referring to the source content.

**Comment by xwu2git** [comment]
The use case is to have the metapublish plugin write to a fifo, where another process picks up the stream-out content for in-line processing. As FIFO must be created beforehand, any writing new file only behavior will prevent such use case.

**Comment by tobiasmo1** [comment]
I understand. I will work with the team to incorporate support for this important use case. I do believe that appending to the file if it already exists (and it can be opened for write) when outputformat="stream" would be acceptable. If an exclusive lock is held by another process we may still return a similar error. Is this expected?

**Comment by tobiasmo1** [comment]
Resolved in DL Streamer v0.7.0 (and above)
