### ISSUE TITLE
vaInitialize failed with error code -1 (unknown libva error),exit

### ISSUE THREAD

**Issue by Surya1208** [opencv/gst-video-analytics#28]
error: XDG_RUNTIME_DIR not set in the environment.
libva info: VA-API version 1.0.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva error: /usr/lib64/dri/i965_drv_video.so has no function __vaDriverInit_1_0
libva info: va_openDriver() returns -1

When i am trying to run vainfo, i am getting the above error. I rebooted the system multiple times and repeated the steps. But the error is not resolved.

PLease help me in resolving the error

**Comment by brmarkus** [comment]
From the GettingStartedGuide "https://github.com/opencv/gst-video-analytics/wiki/Getting-Started-Guide-%5BR3%5D":
#+#+#+
- Check VA-API:
Run vainfo and check that iHD driver is found and initialized successfully
cd ~/gva/gst-video-analytics/scripts  # was cloned on step 2.1 of current instruction
source ./setup_env.sh
vainfo
#+#+#+
Is this what you did?
Installed within a Docker container or "natively" on your host?

**Comment by Surya1208** [comment]
Yes..I followed the same steps as mentioned in the guide...I am installing natively on my host

**Comment by brmarkus** [comment]
Can you double-check whether the installation scripts under "https://github.com/opencv/gst-video-analytics/tree/master/scripts" succeeded?
(e.g. manually checking the repos were sync'ed, build successfully and installed)
=> libdrm built and installed (configure/autogen, make, sudo make install)
=> libva built and installed
=> libva_utils build and installed
==> all via the source code repos?
Or have you installed them via your operating-system's package manager?

**Comment by Surya1208** [comment]
I am not running all the scripts under https://github.com/opencv/gst-video-analytics/tree/master/scripts

I am just running ./install_dependencies.sh and source ./setup_env.sh from the above directory.....

**Comment by dmitryermilov** [comment]
Sorry for off-topic. Wondering, does gst-video-analytics project include i965_drv_video.so (not iHD_drv_video.so)? AFAIK i965_drv_video media driver has been deprecated, it won't support new platforms.

**Comment by brmarkus** [comment]
Looks like the GettingStartedGuide is not complete...
Can you try to call "build_install_libva.sh" and check again, please?

**Comment by Surya1208** [comment]
After calling build_install_libva.sh, we are getting the below errors:

tar: Error is not recoverable: exiting now
./build_install_libva.sh: 15: cd: can't cd to libdrm-2.4.94
./build_install_libva.sh: 16: ./build_install_libva.sh: ./configure: not found
Cloning into 'libva'...
fatal: unable to access 'https://github.com/intel/libva.git/': Could not resolve host: github.com
./build_install_libva.sh: 20: cd: can't cd to libva
./build_install_libva.sh: 21: ./build_install_libva.sh: ./autogen.sh: not found
Cloning into 'libva-utils'...
fatal: unable to access 'https://github.com/intel/libva-utils.git/': Could not resolve host: github.com
./build_install_libva.sh: 25: cd: can't cd to libva-utils
./build_install_libva.sh: 26: ./build_install_libva.sh: ./autogen.sh: not found

**Comment by brmarkus** [comment]
Are you working in a corporate network and probably need to set PROXY env variables (http and https)?

Which OperatingSysten is your HOST running on?

Can you try to run the commands from the script "build_install_libva.sh" manually to see what is failing?

Has "wget" downloaded the tar-file correctly, non-zero file-size?

**Comment by Surya1208** [comment]
Yeah..I am running in a corporate network...The Host is running on Ubuntu 18.04..OK i will try to run the commands manually "build_install_libva.sh

**Comment by umed** [comment]
hi @dmitryermilov , we are using iHD driver within docker, but we ship neither i695 nor iHD

**Comment by umed** [comment]
Hi @Surya1208,

How is it going? Did you succeeded with configuring your environment?
