### ISSUE TITLE
Is it possible to control the font/colors of gvawatermark element ? 

### ISSUE THREAD

**Issue by MhdKAT** [opencv/gst-video-analytics#290]
Hi ! I am trying to run the object line crossing example but I don't like the visuals I get out of gvawatermark.
So I am wondering if it is possible to control the font/color of element that gvawatermark overlays because I can't find this info anywhere in the docs ? Thank you!

**Comment by brmarkus** [comment]
You might want to have a look into this older issue: https://github.com/dlstreamer/dlstreamer/issues/218

> You need to add a call back function at the src pad of gvawatermark element, in face_detection_and_classification, this callback was not set, you can refer to draw_face_attribute sample to learn how.
> 
> If you check the sample code ~/sample/python/draw_face_attribute, the pipeline was setup at the frame call back function of the draw_face_attributes.py file; this function was added at [the src pad of gvawatermark](https://github.com/openvinotoolkit/dlstreamer_gst/blob/master/samples/python/draw_face_attributes/draw_face_attributes.py#L123).
> 
> You might change the color of bbox or text in [the frame call back function](https://github.com/openvinotoolkit/dlstreamer_gst/blob/master/samples/python/draw_face_attributes/draw_face_attributes.py#L38) which was attached to the gvawatermark src pad.

**Comment by MhdKAT** [comment]
Thank you for your reply ! I am wondering whether adding such python probe functions will impact the performance since the video stream is a C/C++ runtime as it will be blocking the pipeline right?

**Comment by brmarkus** [comment]
You haven't mentioned C/C++ before ;-)
It was just an example mentioned.

GVAWatermark is a gstreamer plugin of DL-Streamer developed in C++ (see https://github.com/dlstreamer/dlstreamer/tree/master/gst/elements/gvawatermark).
You will be able to get to the SRC Pad in C/C++ as well via GST APIs.

**Comment by MhdKAT** [comment]
Thank you !
