### ISSUE TITLE
gst-resource-error-quark: base_inference plugin intitialization failed (2)"

### ISSUE THREAD

**Issue by kanagala388** [opencv/gst-video-analytics#31]
Tried running the application with the GPU by updating my pipeline file.Please find the part of the pipeline. 

template": "urisourcebin uri=\"{source[uri]}\" ! concat name=c ! decodebin ! video/x-raw ! videoconvert name=\"videoconvert\" ! gvadetect inference-id=inf0 model=\"{models[person_detection][1][network]}\" model-proc=\"{models[person_detection][1][proc]}\" **device=GPU** name=\"detection\" ! gvametaconvert converter=json method=detection source=\"{source[uri]}\" name=\"jsonmetaconvert\" ! tee name=t ! queue ! gvawatermark ! videoconvert ! autovideosink t. ! queue ! appsink name=appsink",

When i checked the log file i observed the following issue

**{"levelname": "ERROR", "asctime": "2019-10-23 10:47:27,566", "message": "Error on Pipeline <built-in function id>: gst-resource-error-quark: base_inference plugin intitialization failed (2)", "name": "GSTPipeline"}**

Thanks in advance.

I am able to run by adding device=CPU but for GPU i am getting the issue.

**Comment by umed** [comment]
Hi @kanagala388 ,

Can you share a bit more details?

Especisally, you can answer to this questions:

Can you share your final pipeline?
How do you run this pipeline?
What the version of gst-video-analytics are you running?
What the version of gstreamer are you using?
What the version of OpenVINO are you using?
Are you running that pipeline within container or in the host? (probably within container)

We need more details to help you resolve your issue.
