### ISSUE TITLE
docker installation of gst plugins binary version failing

### ISSUE THREAD

**Issue by Mushtaq-BGA** [opencv/gst-video-analytics#33]
Hi,
I have a core-i7 system where i am trying to install the gst-plugins via docker, as i need binary version i am trying to run ./build_docker_image.sh package, but the in between it throws an error(PFA screenshot).

Thanks
Mushtaq
![gst-error1](https://user-images.githubusercontent.com/36155601/69935383-b9cfbc00-14fa-11ea-99b6-cdb89e638647.png)
![gst-error2](https://user-images.githubusercontent.com/36155601/69935384-b9cfbc00-14fa-11ea-881f-3652b2f0d83a.png)

**Comment by brmarkus** [comment]
You need to download OpenVINO on your own (register and download).
Via a Docker argument "OpenVINO_VERSION" you can change the version to use - "2019.3.334" is the default version and therefore a file "l_openvino_toolkit_p_2019.3.334.tgz" is expected.

**Comment by Andruxin52rus** [comment]
Hi @Mushtaq-BGA!
The second (and simplest) option would be to run **./build_docker_image.sh opensource** which will download opensource OpenVINO distribution during build for you. This will go if you don't have requirements on OpenVINO version to use
