### ISSUE TITLE
is this openvino gst-video-analytics only from amd64?

### ISSUE THREAD

**Issue by saket424** [opencv/gst-video-analytics#34]
I was hoping for a docker recipe to build a gst-video-analytics image to run on raspberry pi4 and movidius NCS2. Possible? Does Step18 just need to be skipped?

My docker build attempt failed here

Step 18/97 : RUN mkdir neo && cd neo &&     wget https://github.com/intel/compute-runtime/releases/download/19.31.13700/intel-gmmlib_19.2.3_amd64.deb &&     wget https://github.com/intel/compute-runtime/releases/download/19.31.13700/intel-igc-core_1.0.10-2364_amd64.deb &&     wget https://github.com/intel/compute-runtime/releases/download/19.31.13700/intel-igc-opencl_1.0.10-2364_amd64.deb &&     wget https://github.com/intel/compute-runtime/releases/download/19.31.13700/intel-opencl_19.31.13700_amd64.deb &&     wget https://github.com/intel/compute-runtime/releases/download/19.31.13700/intel-ocloc_19.31.13700_amd64.deb &&     dpkg -i *.deb &&     dpkg-deb -x intel-gmmlib_19.2.3_amd64.deb /home/build/ &&     dpkg-deb -x intel-igc-core_1.0.10-2364_amd64.deb /home/build/ &&     dpkg-deb -x intel-igc-opencl_1.0.10-2364_amd64.deb /home/build/ &&     dpkg-deb -x intel-opencl_19.31.13700_amd64.deb /home/build/ &&     dpkg-deb -x intel-ocloc_19.31.13700_amd64.deb /home/build/ &&     cp -a /home/build/. /

dpkg: error processing archive intel-gmmlib_19.2.3_amd64.deb (--install):
 package architecture (amd64) does not match system (armhf)
dpkg: error processing archive intel-igc-core_1.0.10-2364_amd64.deb (--install):
 package architecture (amd64) does not match system (armhf)
dpkg: error processing archive intel-igc-opencl_1.0.10-2364_amd64.deb (--install):
 package architecture (amd64) does not match system (armhf)
dpkg: error processing archive intel-ocloc_19.31.13700_amd64.deb (--install):
 package architecture (amd64) does not match system (armhf)
dpkg: error processing archive intel-opencl_19.31.13700_amd64.deb (--install):
 package architecture (amd64) does not match system (armhf)
Errors were encountered while processing:
 intel-gmmlib_19.2.3_amd64.deb
 intel-igc-core_1.0.10-2364_amd64.deb
 intel-igc-opencl_1.0.10-2364_amd64.deb
 intel-ocloc_19.31.13700_amd64.deb
 intel-opencl_19.31.13700_amd64.deb

**Comment by umed** [comment]
Hi @saket424 ,

Currently, we do not provide such docker files.

But you can try to get rid of those steps. They are only required if you want to do processing on GPU. Also, remove MediaSDK installation and VAAPI. Probably you will face some different problems that I do not know right now. So, the only advice I can provide is try to play with current Dockerfile.

**Comment by umed** [comment]
There are no comments in 22 days. So, I'm closing it.

Feel free to reopen.
