### ISSUE TITLE
Error Message with vainfo

### ISSUE THREAD

**Issue by Cesaire-Njietche** [opencv/gst-video-analytics#36]
After following the installation steps several times and rebooting the system, I still get this error with the command `vainfo`

libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
libva error: /opt/intel/mediasdk/lib64/iHD_drv_video.so has no function __vaDriverInit_0_32
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit

**Comment by umed** [comment]
Hi @Cesaire-Njietche ,

Sorry for long response. Did you fix your issue?

What is your OS? What version of MediaSDK did you install?

**Comment by Cesaire-Njietche** [comment]
Hi @umed   

I use Ubuntu 16.04 and MediaSDK was installed with the latest version of openvino 2020.1.023. I have an integrated Nvidia GPU.

**Comment by brmarkus** [comment]
It might be similar to this recently reported issue "https://github.com/opencv/gst-video-analytics/issues/30".

> How have you installed libva? Have you installed it via "gst-video-analytics/scripts/build_install_libva.sh" from this repo? The version "VA-API version 0.39.0" looks wrong. Looks like you have a legacy environment.
> [...]
> Can you call the following command, please?
> $> strings /opt/intel/mediasdk/lib64/iHD_drv_video.so | grep vaDriverInit

**Comment by Cesaire-Njietche** [comment]
The command `strings /opt/intel/mediasdk/lib64/iHD_drv_video.so | grep vaDriverInit` outputs `__vaDriverInit_1_4`

**Comment by brmarkus** [comment]
The symbol within your iHD media-driver ("backend") shows that it doesn't fit to your libva ("frontend").

Do you use a "legacy system" where an older version of libva was already installed (for other projects)?
Have you sync'ed and built libva via this script `gst-video-analytics/scripts/build_install_libva.sh`?

**Comment by easychizy** [comment]
Hi @Cesaire-Njietche,

It has been a while for this issue, was it solved?

This seems like you have an environment issue, for example, if your environment variable "LIBVA_DRIVER_NAME" and "LIBVA_DRIVERS_PATH" was set.

Let me know if you still need help or we will close this issue in a week.

Mark

**Comment by adranit** [comment]
Closing the issue due to no updates for a long time. @Cesaire-Njietche  please reopen the issue if it is not resolved yet.
