### ISSUE TITLE
Threads not found by cmake on ubuntu 18.04. OpenVINO 2019 R1 also looks for threads and finds it.

### ISSUE THREAD

**Issue by js07920** [opencv/gst-video-analytics#4]
cfl-nuc:~/gst-video-analytics/build$ cmake ../
-- CMAKE_BUILD_TYPE is undefined. Set default build type Release.
CMake Warning at CMakeLists.txt:25 (message):
  VERSION_PATCH is undefined.  Set default value 0.

CMake Warning at CMakeLists.txt:30 (message):
  GIT_INFO is undefined.  Set default value git_unknown.

-- Host CPU features:
--   3DNOW not supported
--   3DNOWEXT not supported
--   ABM not supported
--   ADX supported
--   AES supported
--   AVX supported
--   AVX2 supported
--   AVX512CD not supported
--   AVX512F not supported
--   AVX512ER not supported
--   AVX512PF not supported
--   BMI1 supported
--   BMI2 supported
--   CLFSH supported
--   CMPXCHG16B supported
--   CX8 supported
--   ERMS supported
--   F16C supported
--   FMA supported
--   FSGSBASE supported
--   FXSR supported
--   HLE not supported
--   INVPCID supported
--   LAHF supported
--   LZCNT supported
--   MMX supported
--   MMXEXT not supported
--   MONITOR supported
--   MOVBE supported
--   MSR supported
--   OSXSAVE supported
--   PCLMULQDQ supported
--   POPCNT supported
--   PREFETCHWT1 not supported
--   RDRAND supported
--   RDSEED supported
--   RDTSCP supported
--   RTM not supported
--   SEP supported
--   SHA not supported
--   SSE supported
--   SSE2 supported
--   SSE3 supported
--   SSE4.1 supported
--   SSE4.2 supported
--   SSE4a not supported
--   SSSE3 supported
--   SYSCALL supported
--   TBM not supported
--   XOP not supported
--   XSAVE supported
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindThreads.cmake:205 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /opt/intel/openvino_2019.1.094/deployment_tools/inference_engine/share/ie_parallel.cmake:103 (find_package)
  /opt/intel/openvino_2019.1.094/deployment_tools/inference_engine/src/extension/CMakeLists.txt:43 (set_ie_threading_interface_for)

-- Configuring incomplete, errors occurred!

**Comment by alalek** [comment]
Check `<build>/CMakeFiles/CMakeError.log` file.
Probably it is due `-Werror` misused flag (you should see it there if it is true).

**Comment by js07920** [comment]
Determining if the include file pthread.h exists failed with the following output:
Change Dir: /home/jsshekha/gst-video-analytics/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_da595/fast"
/usr/bin/make -f CMakeFiles/cmTC_da595.dir/build.make CMakeFiles/cmTC_da595.dir/build
make[1]: Entering directory '/home/jsshekha/gst-video-analytics/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_da595.dir/CheckIncludeFile.c.o
/usr/bin/cc   -Werror -Wuninitialized -Warray-bounds -fstack-protector-strong -std=c++11 -fPIE   -o CMakeFiles/cmTC_da595.dir/CheckIncludeFile.c.o   -c /home/jsshekha/gst-video-analytics/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c
cc1: error: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C [-Werror]
cc1: all warnings being treated as errors
CMakeFiles/cmTC_da595.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_da595.dir/CheckIncludeFile.c.o' failed
make[1]: *** [CMakeFiles/cmTC_da595.dir/CheckIncludeFile.c.o] Error 1
make[1]: Leaving directory '/home/user/gst-video-analytics/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_da595/fast' failed
make: *** [cmTC_da595/fast] Error 2

**Comment by js07920** [comment]
After above comment, I changed the two lines in <project root>/CMakeLists.txt by removing -Werror so that they look like this:
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wuninitialized -Winit-self -Wmaybe-uninitialized -Warray-bounds -fstack-protector-strong")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wuninitialized -Warray-bounds -fstack-protector-strong")

Now, after deleting all files in build directory, cmake gets past thread error but sees new error:
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'gstreamer-1.0'
--   No package 'gstreamer-1.0' found
CMake Error at /usr/local/share/cmake-3.14/Modules/FindPkgConfig.cmake:457 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/share/cmake-3.14/Modules/FindPkgConfig.cmake:642 (_pkg_check_modules_internal)
  gst/common/CMakeLists.txt:13 (pkg_check_modules)

**Comment by alalek** [comment]
That is it.
Workaround: remove misused `-Werror` from CMake script files.

P.S. `-Werror` may be used on build CI with well defined environment/compiler/etc. It should not be enabled by default in user environments.
