### ISSUE TITLE
Running multiple pipelines in a single process

### ISSUE THREAD

**Issue by mtashireva** [opencv/gst-video-analytics#44]
When pipeline object is destroyed/ finalized, the corresponding memory for inference model is not freed which leads to a memory leak.

**Comment by mtashireva** [comment]
WORKAROUND:
Option1. Run each pipeline as a subprocess.
Option2. Cache the inference element from the pipeline in the application.

**Comment by adranit** [comment]
The issue was resolved in OpenVINO2020.2 release.
