### ISSUE TITLE
OSError: libgstvideoanalyticsmeta.so

### ISSUE THREAD

**Issue by kobuworks** [opencv/gst-video-analytics#46]
Hi,
How can I get  "libgstvideoanalyticsmeta.so", Ubuntu was upgraded to 19.10 w/ LK 5.3.0, however the file is not found in /usr/lib/x86_64-linux-gnu/gstreamer-1.0.

Error:
    libgstva = ctypes.CDLL("libgstvideoanalyticsmeta.so")
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libgstvideoanalyticsmeta.so: cannot open shared object file: No such file or directory
----------------------------------------------------------------------

Thanks!
BR/Kobu

**Comment by umed** [comment]
Hi @kobuworks ,

Somehow, `ctypes.CDLL` searches in wrong folder.
Did you run `make install` without any additional environment variables/args?

If so, you should add config for `ldconfig`. Our default installation path is `/usr/lib/gst-video-analytics`. So, to fix your situation you should add config in following location /etc/ld.so.conf.d/gva.conf with this content:

```sh
/usr/lib/gst-video-analytics
```

Let me know if it didn't help.

Sorry, I've missed notification and didn't answer in time.

**Comment by umed** [comment]
Hi @kobuworks ,

is there any updates?

**Comment by kobuworks** [comment]
Hi Umed,
Thanks for your instruction, I'll check this installation from Gstreamer, I'll do it later.
thanks a lot,
BR/Kobu

**Comment by easychizy** [comment]
Hi @kobuworks,

Did you try this issue yet?

We have some update to our product: with the latest 2020.2 release, our product is included in OpenVINO release, there are several options when you want to install it. 

Let me know if you want more information or help with this issue, and if we don't get any response, we will close this issue in a week.

Mark

**Comment by kobuworks** [comment]
Hi Mark,
Thanks for asking, now I'm using OpenVINO2020.2 DL streamer, it's much easier.
Let me close this.
Thanks!!
BR/Kobu
