### ISSUE TITLE
met issue when build docker of fst plufgins

### ISSUE THREAD

**Issue by yangqing-yq** [opencv/gst-video-analytics#49]
when run this command:
$sudo ./build_docker_image.sh package

met below issue:
Step 61/93 : COPY ./l_openvino_toolkit_p_${OpenVINO_VERSION}.tgz .
COPY failed: stat /var/lib/docker/tmp/docker-builder814337069/l_openvino_toolkit_p_2020.1.023.tgz: no such file or directory

**Comment by brmarkus** [comment]
#+#+#+
Please register and download the latest version of OpenVINO™ Toolkit for Linux*. 
#+#+#+
The default version is "2020.1.023", i.e. the Dockerfile expects a file "l_openvino_toolkit_p_${OpenVINO_VERSION}.tgz".
If the downloaded version differs from "2020.1.023" then provide a build argument "OpenVINO_VERSION" to Docker.

**Comment by umed** [comment]
Seems like problem is solved. Feel free to reopen in case of questions.
