### ISSUE TITLE
cmake pkgconfig can't find gstreamer-1.0 pkg conf

### ISSUE THREAD

**Issue by js07920** [opencv/gst-video-analytics#5]
-- Found Threads: TRUE  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'gstreamer-1.0'
--   No package 'gstreamer-1.0' found
CMake Error at /usr/local/share/cmake-3.14/Modules/FindPkgConfig.cmake:457 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/share/cmake-3.14/Modules/FindPkgConfig.cmake:642 (_pkg_check_modules_internal)
  gst/common/CMakeLists.txt:13 (pkg_check_modules)

**Comment by js07920** [comment]
The directions of this project do not specify the pre-requisites. I installed following after above comment and now cmake proceeds.
sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

**Comment by alalek** [comment]
BTW, Did you try to [build via docker](https://github.com/opencv/gst-video-analytics/wiki/Build-docker-image-from-sources-and-run-docker-container)?

**Comment by SDxKeeper** [comment]
There are script available to install dependencies gst-video-analytics/scripts/install_dependencies.sh

**Comment by js07920** [comment]
@alalek. I did not yet build via docker.
@SDxKeeper : Thanks for pointing out the script. It's not mentioned in the "Build-on-host-machine" wiki. Furthermore, it downloads MediaSDK. But if OpenVINO is installed (I use 2019 R1), the script should check OpenVINO based paths for mediasdk. My preference is to use MediaSDK and if needed OpenCV that is installed as part of OpenVINO.

**Comment by SDxKeeper** [comment]
@js07920 yes this is expected behavior,  because gstreamer video analytics plugins were released for openvino 2018 r5, which had incompatible media SDK stack. In next release with official support of openvino 2019 r1, this dependency will be removed for package based installations.

**Comment by Andruxin52rus** [comment]
Hi @js07920 ! We've made some significant improvements in our documentation. You're welcome to review and try it: https://github.com/opencv/gst-video-analytics/wiki/Getting-Started-Guide-%5BR1.2%5D
If issue with missing packages is not resolved for you, please reopen this issue with additional details
