### ISSUE TITLE
iHD_drv_video.so init failed

### ISSUE THREAD

**Issue by thaon3326** [opencv/gst-video-analytics#51]
when i run vainfo , it notice error:
libva info: VA-API version 1.4.1
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_4
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
libva error: /opt/intel/mediasdk/lib64/iHD_drv_video.so init failed
libva info: va_openDriver() returns 18
vaInitialize failed with error code 18 (invalid parameter),exit

I try reinstall but it show error the same!

**Comment by brmarkus** [comment]
This looks like you don't have an (integrated) Intel GPU, but maybe an AMD or NVIDIA graphics card...
I just tested this on one of my Linux development machines (Intel CPU, but no Intel GPU plugged in) and it looks exactly like yours, when calling `vainfo`:

```
$> vainfo
libva info: VA-API version 1.4.1
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_4
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
libva error: /opt/intel/mediasdk/lib64/iHD_drv_video.so init failed
libva info: va_openDriver() returns 18
vaInitialize failed with error code 18 (invalid parameter),exit
```
The plugin is based on Intel-MediaSDK and requires an underlying Intel-based HW-accelerated video decoder.

**Comment by adranit** [comment]
Closing the issue due to no updates for a long time. @thaon3326 please reopen the issue if it is not resolved yet.
