### ISSUE TITLE
`libgstvideoanalyticsmeta.so*` and  `libcpu_extension.so*` libraries should be installed in non-gst-plugins directory

### ISSUE THREAD

**Issue by lsandov1** [opencv/gst-video-analytics#55]
`libgstvideoanalyticsmeta.so*` and `libcpu_extension.so*` are not gst-plugins thus it should reside on `<prefix>/lib64` folder instead of `<prefix>/lib64/gst-plugins-1.0/`

**Comment by umed** [comment]
Hi there,

Yeah, there is such problem. It will be fixed by upcoming release. Let me know if you notice anything else.

Thanks for your issue.

**Comment by umed** [comment]
already implemented
