### ISSUE TITLE
ERROR: from element /GstPipeline:pipeline0/GstDecodeBin:decodebin0/GstQTDemux:qtdemux0: Internal data stream error.

### ISSUE THREAD

**Issue by 1000sprites** [opencv/gst-video-analytics#58]
root@k3s:~/gst-video-analytics/samples/shell# ./face_detection_and_classification.sh $VIDEO_EXAMPLES_DIR/Pexels.mp4
[setup_env.sh] GStreamer-plugins environment initialized
[setlocale.sh] C locale is set
Running sample with the following parameters:
GST_PLUGIN_PATH=/root/gst-video-analytics/scripts/../build/intel64/Release/lib:/usr/lib/gst-video-analytics/:/root/gst-video-analytics/
LD_LIBRARY_PATH=/opt/intel/dldt/inference-engine/external/hddl/lib
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Redistribute latency...
Redistribute latency...
ERROR: from element /GstPipeline:pipeline0/GstDecodeBin:decodebin0/GstQTDemux:qtdemux0: Internal data stream error.
Additional debug info:
qtdemux.c(6073): gst_qtdemux_loop (): /GstPipeline:pipeline0/GstDecodeBin:decodebin0/GstQTDemux:qtdemux0:
streaming stopped, reason not-negotiated (-4)
ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
Freeing pipeline ...

**Comment by 1000sprites** [comment]
root@k3s:~/gst-video-analytics/samples/shell# ./face_detection_and_classification.sh $VIDEO_EXAMPLES_DIR/Pexels.avi
[setup_env.sh] GStreamer-plugins environment initialized
[setlocale.sh] C locale is set
Running sample with the following parameters:
GST_PLUGIN_PATH=/root/gst-video-analytics/scripts/../build/intel64/Release/lib:/usr/lib/gst-video-analytics/:/root/gst-video-analytics/
LD_LIBRARY_PATH=/opt/intel/dldt/inference-engine/external/hddl/lib
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Redistribute latency...
Redistribute latency...
ERROR: from element /GstPipeline:pipeline0/GstDecodeBin:decodebin0/GstAviDemux:avidemux0: Internal data stream error.
Additional debug info:
gstavidemux.c(5780): gst_avi_demux_loop (): /GstPipeline:pipeline0/GstDecodeBin:decodebin0/GstAviDemux:avidemux0:
streaming stopped, reason not-negotiated (-4)
ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
Freeing pipeline ...

**Comment by brmarkus** [comment]
Can you confirm the variable "$VIDEO_EXAMPLES_DIR" contains a valid path?

**Comment by 1000sprites** [comment]
@brmarkus yes, I can. I has solved it by video-sink=ximagesink.

**Comment by umed** [comment]
feel free to reopen in case of questions

**Comment by PythonImageDeveloper** [comment]
@1000sprites 
Can you solved the problem? with ximagesink also I have same error.
