### ISSUE TITLE
GPU decode and GPU inference is broken

### ISSUE THREAD

**Issue by vtpl1** [opencv/gst-video-analytics#59]
Hi,
If I run 
`~/gst-video-analytics/samples/benchmark# ./benchmark.sh file.avi GPU GPU
`
Then the following error occurs:

WARNING: erroneous pipeline: could not link vaapipostproc0 to gvadetect0, gvadetect0 can't handle caps video/x-raw(memory:VASurface)

**Comment by brmarkus** [comment]
Can you briefly describe your system-setup, please? Are you running e.g. Ubuntu with X/X11? Do you have an Intel GPU available?
Are you testing within a container or outside a container?
Have you set ENV variables like DISPLAY?

**Comment by brmarkus** [comment]
Which version(s) are you using?

**Comment by vtpl1** [comment]
I am using docker version of the latest commit (24366c0).
With the following arguments:

`./build_docker_image.sh package test`

```
xhost +
docker run -it --rm --privileged --net=host --device /dev/dri \
    \
    -v ~/.Xauthority:/root/.Xauthority \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e DISPLAY=$DISPLAY \
    -e HTTP_PROXY=$HTTP_PROXY \
    -e HTTPS_PROXY=$HTTPS_PROXY \
    -e http_proxy=$http_proxy \
    -e https_proxy=$https_proxy \
    \
    -v ~/gva/data/models/intel:/root/intel_models:ro \
    -v ~/gva/data/models/common:/root/common_models:ro \
    -e MODELS_PATH=/root/intel_models:/root/common_models \
    \
    -v ~/gva/data/video:/root/video-examples:ro \
    -e VIDEO_EXAMPLES_DIR=/root/video-examples \
    \
    -v `pwd`:/root/gst-video-analytics \
    -w /root/gst-video-analytics/samples \
    \
    gst-video-analytics:test
```

I have modified the `docker/binaries.Dockerfile` to use latest OpenVino:

`ARG OpenVINO_VERSION=2020.2.120`

The base OS is Ubuntu 16

```
uname -a
Linux test_pc 4.15.0-96-generic #97~16.04.1-Ubuntu SMP Wed Apr 1 03:03:31 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

```
Here is the snippet of the hardware info.

```
cat /proc/cpuinfo
processor	: 11
vendor_id	: GenuineIntel
cpu family	: 6
model		: 158
model name	: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
stepping	: 10
microcode	: 0xca
cpu MHz		: 1584.230
cache size	: 12288 KB
physical id	: 0
siblings	: 12
core id		: 5
cpu cores	: 6
apicid		: 11
initial apicid	: 11
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit
bogomips	: 6384.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:
```

**Comment by brmarkus** [comment]
What else have you changed ;-) ?
So I downloaded "l_openvino_toolkit_p_2020.2.120.tgz". I modified the Dockerfile to use the version "2020.2.120", then build the Docker container and run it. I can run various samples, get the video plus metadata rendered.

But I don't have the benchmark folder, don't have "benchmark.sh" in the container...

I don't know whether your SOC with the CPU "Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz" has an Intel-GPU... Can you check with e.g. `lspci | grep VPA` on your HOST, please?

**Comment by vtpl1** [comment]
I ran the Benchmark app from [samples/benchmark](https://github.com/opencv/gst-video-analytics/tree/master/samples/benchmark).

The  `gst-inspect-1.0 gvadetect` does not seem to have `video/x-raw(memory:VASurface)`
```
Pad Templates:
  SINK template: 'sink'
    Availability: Always
    Capabilities:
      video/x-raw
                 format: { (string)BGRx, (string)BGRA, (string)BGR, (string)NV12, (string)I420 }
                  width: [ 1, 2147483647 ]
                 height: [ 1, 2147483647 ]
              framerate: [ 0/1, 2147483647/1 ]
      video/x-raw(memory:VASurface)
                 format: { (string)NV12 }
                  width: [ 1, 2147483647 ]
                 height: [ 1, 2147483647 ]
              framerate: [ 0/1, 2147483647/1 ]
  
  SRC template: 'src'
    Availability: Always
    Capabilities:
      video/x-raw
                 format: { (string)BGRx, (string)BGRA, (string)BGR, (string)NV12, (string)I420 }
                  width: [ 1, 2147483647 ]
                 height: [ 1, 2147483647 ]
              framerate: [ 0/1, 2147483647/1 ]
      video/x-raw(memory:VASurface)
                 format: { (string)NV12 }
                  width: [ 1, 2147483647 ]
                 height: [ 1, 2147483647 ]
              framerate: [ 0/1, 2147483647/1 ]
```
The device has the following:
```
lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation Device 3e92
```

**Comment by brmarkus** [comment]
Yes, the benchmark folder and script exists in the repo - but is not part of the Docker container in my case... In your shown command-line of `docker run` I don't see it is volume-mapped into the container.

What have you changed to get it into the container?

Can you describe the file `file.avi` you use, maybe using the tool `mediainfo` or similar, which codecs, which streams? Depending on the contained streams the pipeline to demux and decode (and post-process) the stream will be different.

**Comment by vtpl1** [comment]
are you using package (binary) version or opensource version?
> Yes, the benchmark folder and script exists in the repo - but is not part of the Docker container in my case... 
By the way in both the cases
`COPY . gst-video-analytics` 
this command copies the entire repo inside the container.

**Comment by brmarkus** [comment]
I called `./build_docker_image.sh package test` (from within the folder `docker`) like you showed above, i.e. I used the `package` version - for which I have downloaded `l_openvino_toolkit_p_2020.2.120.tgz` from `software.intel.com` and updated the Dockerfile `docker/binaries.Dockerfile` with the version information.

In my case I don't see the folder `benchmark` inside the container (but I see it on the HOST)...:

```
:~/gst-video-analytics/samples# ll
total 32
drwxrwxr-x 7 root root 4096 Oct 14  2019 ./
drwxr-xr-x 1 root root 4096 Mar 31 06:45 ../
-rw-rw-r-- 1 root root  561 Oct 14  2019 CMakeLists.txt
drwxrwxr-x 4 root root 4096 Oct 14  2019 cpp/
drwxrwxr-x 2 root root 4096 Oct 14  2019 model_downloader_configs/
drwxrwxr-x 2 root root 4096 Oct 14  2019 model_optimizer_configs/
drwxrwxr-x 2 root root 4096 Oct 14  2019 model_proc/
drwxrwxr-x 5 root root 4096 Oct 14  2019 shell/
```

Are the "normal" scripts for e.g. face-detection working for you using various video files?

Maybe your video file contains an "exotic" video stream?

**Comment by vtpl1** [comment]
Let me recheck.
The folder structure that you are showing is from older commit (v0.7.0) not (v1.0.0).
The video stream works for CPU decoding and GPU inference combination.
Let me recheck with other videos.

**Comment by brmarkus** [comment]
I used the latest commit (24366c04d813ad0ea273da91accafda636a2618b) - let me check as well whether Docker just did an incremental build and now I have a Frankenstein of an old Docker- and a new Docker-image of the container...

**Comment by brmarkus** [comment]
Ah, ok, I used your command line to build the container - with a tag "test", but haven't used the tag when starting the container... I have two container images, with "latest" and with "test" tag.

**Comment by brmarkus** [comment]
Will rebuild the container from scratch.

**Comment by brmarkus** [comment]
> Let me recheck.
> The folder structure that you are showing is from older commit (v0.7.0) not (v1.0.0).
> The video stream works for CPU decoding and GPU inference combination.
> Let me recheck with other videos.

The video worked for CPU-decoding but not for GPU-decoding? Then CPU-decoding might use a SW-video-decoder-codec - it might fail if for GPU-decoding there is no GPU-HW-accelerated-decoder-codec supported for your Intel-GPU - does the video file contain an "exotic" video stream? E.g. an Intel-GPU doesn't have a OGG-Vorbis-Video-HW-decoder... There won't be a VAAPI- or MediaSDK-video-decoder for the GPU.

**Comment by brmarkus** [comment]
Ok, I have re-built the Docker container image from scratch - but still don't have the "benchmark" folder inside the container.

**Comment by vtpl1** [comment]
The samples folder should look like this:
```
CMakeLists.txt  
README.md  
benchmark  
cpp  
download_models.sh  
gst_launch  
model_proc  
models.lst  
python
```

**Comment by brmarkus** [comment]
On the HOST, outside the container, yes, the samples folder looks like this:

```
$> ll
total 44
drwxrwxr-x  7 4096 Apr 16 12:57 .
drwxrwxr-x 14 4096 Apr 16 12:58 ..
drwxr-xr-x  2 4096 Apr 16 12:57 benchmark
-rw-r--r--  1  616 Apr 16 12:57 CMakeLists.txt
drwxr-xr-x  3 4096 Apr 16 12:57 cpp
-rwxr-xr-x  1  497 Apr 16 12:57 download_models.sh
drwxr-xr-x  7 4096 Apr 16 12:57 gst_launch
drwxrwxr-x  2 4096 Apr 16 12:57 model_proc
-rw-r--r--  1  369 Apr 16 12:57 models.lst
drwxr-xr-x  3 4096 Apr 16 12:57 python
-rw-r--r--  1 2780 Apr 16 12:57 README.md
```
But not for me inside the container. Looks like it gets overridden by build artifacts?
Strange...

**Comment by vtpl1** [comment]
The following command works:
`~/gst-video-analytics/samples/benchmark# ./benchmark.sh /root/video-examples/head-pose-face-detection-female-and-male.mp4 `

`~/gst-video-analytics/samples/benchmark# ./benchmark.sh /root/video-examples/head-pose-face-detection-female-and-male.mp4 CPU GPU`
The following command also works.

`~/gst-video-analytics/samples/benchmark# ./benchmark.sh /root/video-examples/head-pose-face-detection-female-and-male.mp4 GPU GPU`

But the avi does not work. 
Let me investigate further.

**Comment by brmarkus** [comment]
You might want to try the tool "mediainfo" (for Linux and MS-Win) to look into which codecs are contained/muxed into the AVI. Looks like there is no GPU-video-codec for it.
If the (first) embedded elementary stream inside the video container is MJPEG, AVC, HEVC, VC1, VP8, VP9, AV1 then the GPU should be able to decode it, otherwise the gstreamer pipeline would need to fallback to SW-codec.

**Comment by easychizy** [comment]
Hi @vtpl1 ,
You probably don't have GPU enabled, here are several checks:
1. The benchmark script requires 2 arguments, the first GPU is inference, the second is for video acceleration, they requires different driver and UMD support. Could you try "CPU GPU" or "GPU CPU" to see if the problem goes away?
2. DL Streamer support Ubuntu 18.04, this means the kernel driver model. Ubuntu 16.04 might not have latest driver, so if you switching to Ubuntu 18.04, the problem might be gone naturally.
3. The processor should be OK, but you need to check if openCL driver is installed correctly, 'clinfo' command should give you > 1 device number. This is the requirement for inference on GPU.

Mark

**Comment by vtpl1** [comment]
@brmarkus thank you for your help.
Another issue I have found that while decoding is happening in GPU then gvatracker does not work.
Should I open a new issue for that?

**Comment by vtpl1** [comment]
Hi Mark,
Thank you for your reply, the issue was with the AVI file. In the mean while I switched to Ubuntu 18.04 will check in Ubuntu 16.04 as host machine and report back.


In the mean while I stumbled upon another issue. I have modified the 
[vehicle_pedestrian_tracking.txt](https://github.com/opencv/gst-video-analytics/files/4488994/vehicle_pedestrian_tracking.txt) file to include GPU decoding.

When GPU decoding is enabled the gvatrack does not allow to create the pipeline.
The following works:
```
gst-launch-1.0 filesrc location=/root/video-examples/person-bicycle-car-detection.mp4 ! decodebin ! videoconvert ! video/x-raw,format=BGRx ! gvadetect model=/root/intel_models/intel/person-vehicle-bike-detection-crossroad-0078/FP32/person-vehicle-bike-detection-crossroad-0078.xml model-proc=./model_proc/person-vehicle-bike-detection-crossroad-0078.json inference-interval=10 threshold=0.6 pre-process-backend=ie device=GPU ! queue ! gvatrack tracking-type=short-term ! queue ! gvaclassify model=/root/intel_models/intel/person-attributes-recognition-crossroad-0230/FP32/person-attributes-recognition-crossroad-0230.xml model-proc=./model_proc/person-attributes-recognition-crossroad-0230.json reclassify-interval=10 pre-process-backend=ie device=GPU object-class=person ! queue ! gvaclassify model=/root/intel_models/intel/vehicle-attributes-recognition-barrier-0039/FP32/vehicle-attributes-recognition-barrier-0039.xml model-proc=./model_proc/vehicle-attributes-recognition-barrier-0039.json reclassify-interval=10 pre-process-backend=ie device=GPU object-class=vehicle ! queue ! gvawatermark ! videoconvert ! fpsdisplaysink video-sink=xvimagesink sync=true
```
But following does not work:
```
gst-launch-1.0 filesrc location=/root/video-examples/person-bicycle-car-detection.mp4 ! decodebin ! vaapipostproc ! video/x-raw(memory:VASurface) ! gvadetect model=/root/intel_models/intel/person-vehicle-bike-detection-crossroad-0078/FP32/person-vehicle-bike-detection-crossroad-0078.xml model-proc=./model_proc/person-vehicle-bike-detection-crossroad-0078.json inference-interval=10 threshold=0.6 pre-process-backend=vaapi device=GPU ! queue ! gvatrack tracking-type=short-term ! queue ! gvaclassify model=/root/intel_models/intel/person-attributes-recognition-crossroad-0230/FP32/person-attributes-recognition-crossroad-0230.xml model-proc=./model_proc/person-attributes-recognition-crossroad-0230.json reclassify-interval=10 pre-process-backend=vaapi device=GPU object-class=person ! queue ! gvaclassify model=/root/intel_models/intel/vehicle-attributes-recognition-barrier-0039/FP32/vehicle-attributes-recognition-barrier-0039.xml model-proc=./model_proc/vehicle-attributes-recognition-barrier-0039.json reclassify-interval=10 pre-process-backend=vaapi device=GPU object-class=vehicle ! queue ! gvawatermark ! videoconvert ! fpsdisplaysink video-sink=xvimagesink sync=true
```

`WARNING: erroneous pipeline: could not link queue0 to gvatrack0`

**Comment by easychizy** [comment]
Hi @vtpl1 
I doubt this is related to the pad capability since some pad have both GPU and CPU support but some don't could this be the problem?
The problem seems to be in the connection between queue0 and gvatrack, gvatrack seems only support CPU. If the topology is to connect vaapiostproc with gvatrack, then it could be the problem.
Mark

**Comment by easychizy** [comment]
Hi @vtpl1 
Sorry for the late response.
Back to your original question, I want to check your input stream.
Could you run "gst-discoverer-1.0 file.avi" and post the result?
Mark

**Comment by umed** [comment]
Hi @vtpl1 ,

Current version of gvatrack does not support i420. So, when you use decoding on GPU you have to do conversion (e.g. by videoconvert) from i420 to RGB before gvatrack

**Comment by umed** [comment]
@vtpl1 , correction:

GPU decoder will produce VASurfaces (video memory) in NV12 color format (not i420).
gvatrack supports neither VASurfaces (video memory) nor NV12.

_i420 is not supported too_

You will have to convert VASurface to system memory and colorformat to BGR.

**Comment by vtpl1** [comment]
@easychizy 
`gst-discoverer-1.0 file.avi`
reveals the following
```
Topology:
  container: Audio Video Interleave (AVI)
    video: ITU H.264 (Baseline Profile)

Properties:
  Duration: 0:20:05.518518518
  Seekable: yes
  Live: no
  Tags: 
      video codec: ITU H.264
      bitrate: 3991927
      container format: AVI

```
