### ISSUE TITLE
Multi-channel identification in the python

### ISSUE THREAD

**Issue by vtpl1** [opencv/gst-video-analytics#60]
Hi,
How to identify each channel uniquely in pad probe callback in python for multi channel pipeline?

**Comment by easychizy** [comment]
Hi @vtpl1 
Sorry for the late response, I think you can figure out from the message object, it has a "src" field.
You can check MessageType in call back and check the channel info.
https://gstreamer.freedesktop.org/documentation/gstreamer/gstmessage.html?gi-language=python#GstMessageType
Mark

**Comment by mikhail-nikolskiy** [comment]
@vtpl1,

You will need to assign different (unique) name in each channel, ex
channel#1: ... ! gvawatermark name=gvawatermark1 ! ...
channel#2: ... ! gvawatermark name=gvawatermark2 ! ...

then you can set callback for each channel (in the loop)
    pad = pipeline.get_by_name("gvawatermark1").get_static_pad("src")
    pad.add_probe(Gst.PadProbeType.BUFFER, pad_probe_callback)

    pad = pipeline.get_by_name("gvawatermark2").get_static_pad("src")
    pad.add_probe(Gst.PadProbeType.BUFFER, pad_probe_callback)
