### ISSUE TITLE
RPi + NCSv2 support

### ISSUE THREAD

**Issue by fischermario** [opencv/gst-video-analytics#63]
Are there any plans to support GStreamer Video Analytics Plugin on the Raspberry Pi (running Raspbian) with a NCSv2 (Myriad plugin) attached to it?

I have not tried to build the plugin because the docs imply that the whole stack heavily relies on components that are not available on Raspbian (e.g. OpenCL, Intel Media SDK, LibVA).

**Comment by umed** [comment]
Hi @fischermario ,

Those libraries are required if you want to use intel graphics to execute inference. There shouldn’t be any problems to run plugins on your setup.

**Comment by adranit** [comment]
The issue is closed due to lack of updates for a long time.
