### ISSUE TITLE
Overall pipeline latency for live rtsp source

### ISSUE THREAD

**Issue by vtpl1** [opencv/gst-video-analytics#64]
For the rtsp stream source the overall pipeline latency is becoming in terms of munites.

To reproduce the problem change the face_detection_and_classification.sh

if we add the following:

```
elif [[ $INPUT == "rtsp://"* ]]; then
  SOURCE_ELEMENT="rtspsrc location=${INPUT} ! rtph264depay ! h264parse"
elif [[ $INPUT == *"://"* ]]; then
  SOURCE_ELEMENT="urisourcebin buffer-size=4096 uri=${INPUT}"

```
The issue arises when the RTSP source is streaming at 25 FPS but the overall pipeline processing FPS is 5. 
We can not do frame drop at rtspsrc as we need to decode all the frames at 25 FPS to eliminate the artifacts in decoding. The frames need to be dropped after decoding.

Is there any way to solve the issue?

**Comment by easychizy** [comment]
Hi @vtpl1,

Sorry for the late response, if you remove any GVA element but just the GStreamer elements and keep the fakesink to minimum the output delay, would the FPS number improved?

So I think we should figure out which element cause the delay, do you agree?

Mark

**Comment by adranit** [comment]
Hi @vtpl1, 
Is there any updates for the issue?

Thanks,
Anton

**Comment by adranit** [comment]
The issue is closed due to lack of updates for a long time.
