### ISSUE TITLE
gvametaconvert info log is missing category

### ISSUE THREAD

**Issue by alokpr** [opencv/gst-video-analytics#65]
The dump-detection format does not use gvametaconvert debug-log category:

https://github.com/opencv/gst-video-analytics/blob/24366c04d813ad0ea273da91accafda636a2618b/gst/elements/gvametaconvert/converters.cpp#L29

This makes it impossible to filter gvametaconvert info logs.

**Comment by adranit** [comment]
planned to 2020.4 release

**Comment by adranit** [comment]
Fixed in 2020.4 (v1.1)
