### ISSUE TITLE
Any limits on max stream density?

### ISSUE THREAD

**Issue by CACUser** [opencv/gst-video-analytics#66]
This is more a question than an issue. In the benchmark sample - there is a sample on how to use multi-channel video analytics pipelines - by using specifying the whole pipeline from filesrc onwards multiple times, with the number of pipeline being equal to number of streams to process. I have tried to look in documentation - but did not see a limit to how many streams can be processed in this way simultaneously. Any pointers or links to specific documentation would be helpful.

**Comment by easychizy** [comment]
Hi @CACUser,

There is no software limitation to the number of streams that can be supported in this way, but the practical limit will be determined by the specific platform on which you are running and its resources (cores, memory, iGPU). To try out different Intel HW you can use Intel’s dev cloud …. 

For your specific hardware we recommend incrementing the number of pipelines with our benchmark sample until the resulting FPS drops below your requirement. If you need to increase the number of streams but don’t need to perform inference on every frame you can further configure the pipeline using the inference-interval property.

If you want to try Intel DevCloud, you can create account and access via following link:
https://www.intel.com/content/www/us/en/develop/tools/devcloud.html

Mark

**Comment by CACUser** [comment]
Thanks!
