### ISSUE TITLE
Can't get object_id via Python

### ISSUE THREAD

**Issue by vtimofeev01** [opencv/gst-video-analytics#69]
please help! 
1) how i get an object_id after tracking in python
2) after tracking 'reid_embedding' vector desapears from ROIs, but i need it later

Thank U
Vasili

**Comment by umed** [comment]
hey @vtimofeev01 ,

> 1. how i get an object_id after tracking in python

yeah, there is missing function. We will add it in upcoming release. Currently, you can iterate through meta and find the one that has `object_id` field. Let me know if you need more details.

> 2. after tracking 'reid_embedding' vector desapears from ROIs, but i need it later

We are aware of the issue and working towards a resolution.

**Comment by vtimofeev01** [comment]
Thank U!
Please show me how to iterate over meta in python?

**Comment by vtimofeev01** [comment]
I found a way like this. is it right?

`    def get_object_id_from_roi(r):
        param = r.meta()._params
        while param:
            t = Tensor(param.contents.data)
            if t.name() == 'object_id':
                return t['id']
            param = param.contents.next`

**Comment by umed** [comment]
@vtimofeev01 , yeah, I think that is it. Don't forget to return `null` if there is no `object_id`.

*sorry I updated your comment to enable syntax highlighting*
