### ISSUE TITLE
face detection sample doesn't run 

### ISSUE THREAD

**Issue by js07920** [opencv/gst-video-analytics#7]
```
user@cfl-nuc:~/gst-video-analytics/samples/shell$ ./face_detection_and_classification.sh ~/videos/input.mp4 
[setup_env.sh] GStreamer-plugins environment initialized
Running sample with the following parameters:
GST_PLUGIN_PATH=:/home/user/gst-video-analytics/build/intel64/Release/lib
LD_LIBRARY_PATH=/opt/intel/common/mdf/lib64:/opt/intel/openvino_2019.1.094/opencv/lib:/opt/intel/opencl:/opt/intel/openvino_2019.1.094/deployment_tools/inference_engine/external/hddl/lib:/opt/intel/openvino_2019.1.094/deployment_tools/inference_engine/external/gna/lib:/opt/intel/openvino_2019.1.094/deployment_tools/inference_engine/external/mkltiny_lnx/lib:/opt/intel/openvino_2019.1.094/deployment_tools/inference_engine/external/tbb/lib:/opt/intel/openvino_2019.1.094/deployment_tools/inference_engine/lib/intel64:/opt/intel/openvino_2019.1.094/openvx/lib:
WARNING: erroneous pipeline: no element "fpsdisplaysink"
user@cfl-nuc:~/gst-video-analytics/samples/shell$ 

user@cfl-nuc:~/gst-video-analytics/samples/shell$ echo $MODELS_PATH 
/home/user/ov_models/
user@cfl-nuc:~/gst-video-analytics/samples/shell$ echo $MODELS_DIR
/home/user/ov_models/
user@cfl-nuc:~/gst-video-analytics/samples/shell$ 
```

**Comment by SDxKeeper** [comment]
Fpsdisplaysink is part of gstreamer1.0-plugins-bad which is listed in install dependencies script.

**Comment by js07920** [comment]
I installed following and get an error.

`$ sudo apt-get install autoconf libtool libdrm-dev xorg xorg-dev openbox libx11-dev     libgl1-mesa-glx libgl1-mesa-dev     libgstreamer1.0-0 gstreamer1.0-plugins-base libgstreamer1.0-dev     libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-bad gstreamer1.0-libav     gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-tools     libgstreamer-plugins-bad1.0-dev libva-dev gstreamer1.0-vaapi `


App:
`user@cfl-nuc:~/gst-video-analytics/samples/shell$ ./face_detection_and_classification.sh ~/videos/input.mp4 
[setup_env.sh] GStreamer-plugins environment initialized
Running sample with the following parameters:
GST_PLUGIN_PATH=./../../scripts/../samples/../build/intel64/Release/lib
LD_LIBRARY_PATH=/opt/intel/common/mdf/lib64:/opt/intel/openvino_2019.1.094/opencv/lib:/opt/intel/opencl:/opt/intel/openvino_2019.1.094/deployment_tools/inference_engine/external/hddl/lib:/opt/intel/openvino_2019.1.094/deployment_tools/inference_engine/external/gna/lib:/opt/intel/openvino_2019.1.094/deployment_tools/inference_engine/external/mkltiny_lnx/lib:/opt/intel/openvino_2019.1.094/deployment_tools/inference_engine/external/tbb/lib:/opt/intel/openvino_2019.1.094/deployment_tools/inference_engine/lib/intel64:/opt/intel/openvino_2019.1.094/openvx/lib:

Setting pipeline to PAUSED ...

Pipeline is PREROLLING ...
Got context from element 'fps-display-video_sink-actual-sink-vaapi': gst.vaapi.Display=context, gst.vaapi.Display=(GstVaapiDisplay)"\(GstVaapiDisplayGLX\)\ vaapidisplayglx1";

ERROR: from element /GstPipeline:pipeline0/GstDecodeBin:decodebin0/GstVaapiDecodeBin:vaapidecodebin0/GstVaapiDecode:vaapidecode0: No valid frames decoded before end of stream
Additional debug info:
gstvideodecoder.c(1161): gst_video_decoder_sink_event_default (): /GstPipeline:pipeline0/GstDecodeBin:decodebin0/GstVaapiDecodeBin:vaapidecodebin0/GstVaapiDecode:vaapidecode0:
no valid frames found
ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
Freeing pipeline ...
user@cfl-nuc:~/gst-video-analytics/samples/shell$`

**Comment by js07920** [comment]
Using an avi file instead of mp4 worked.

**Comment by Andruxin52rus** [comment]
Hi @js07920 ! We made R1.2 release and updated our instructions recently: https://github.com/opencv/gst-video-analytics/wiki/Getting-Started-Guide-%5BR1.2%5D. It was evaluated by several QA engineers and no such bugs were found. You're welcome to setup your system from scratch (or use docker installation). Please reopen the issue if bug will reproduce

**Comment by duongthao1218** [comment]
You need to install the gstreamer1.0-plugins-bad by `sudo apt-get install gstreamer1.0-plugins-bad`
