### ISSUE TITLE
 gst-video-analytics/thirdparty/vas/DownloadVas.cmake  often fail when download 3rd libs in China

### ISSUE THREAD

**Issue by pingxiyan** [opencv/gst-video-analytics#70]
When I built gva, it often failed when downloaded 3rd lib "https://downloadmirror.intel.com/29445/eng/vasot.2020.1.ubuntu.opencv.4.3.tar.xz".

However I found it would decrease fail occur when I increased try download times.
Just modified file: gst-video-analytics/thirdparty/vas/DownloadVas.cmake 
- set(WGET_RETRY_COUNT 1)
+ set(WGET_RETRY_COUNT 6)

**Comment by umed** [comment]
hey @pingxiyan ,

Thanks! will update retry count 👍

**Comment by adranit** [comment]
Fixed in 2020.4 (v1.1)
