### ISSUE TITLE
Not able to Execute elements Pipeline Successfully

### ISSUE THREAD

**Issue by sanchitjain04** [opencv/gst-video-analytics#73]
I am new to Openvino DL streamer, i was trying to implement few of the models mentioned in the intel's pre trained models github repo: [https://github.com/opencv/open_model_zoo/blob/master/models/intel/index.md](url) , to be precise pipeline which includes vehicle tracking, vehicle attribute recognition and license number plate detection, i downloaded the below models for my pipeline:

For vehicle detection, tracking and license plate detection: vehicle-license-plate-detection-barrier-0106
For attribute recognition: vehicle-attributes-recognition-barrier-0039

My Pipeline looks like this:

![piepline](https://user-images.githubusercontent.com/38455473/85515842-3226d780-b61b-11ea-8033-2638b35665af.png)

After executing this pipeline i am unable to generate the output file its showing 0 Bytes, I would like to ask what mistake i am doing while creating the pipeline as i am not getting desired output.

Thank you.

**Comment by brmarkus** [comment]
Instead of pasting a screenshot of your script, can you provide a textual content, please? I'm too lazy to re-type everything...

Is the sample-script "~/gst-video-analytics/samples/shell/vehicle_license_plate_detection_barrier_0106.sh /my/path/cars.mp4" working for you, just to clarify your environment is functional?

**Comment by sanchitjain04** [comment]
The textual content is:



DEVICE=${2:-CPU}

MODEL=models/intel/vehicle-license-plate-detection-barrier-0106/FP16/vehicle-license-plate-detection-barrier-0106.xml
MODEL2=models/intel/vehicle-attributes-recognition-barrier-0039/FP16/vehicle-attributes-recognition-barrier-0039.xml
INPUT_FILE=cars.mp4
INFERENCE_INTERVAL=10
OUTPUT_FILE=car_license_tracking_output.mp4

PIPELINE="filesrc location=$INPUT_FILE ! decodebin !  \
    videoconvert n-threads=4 ! capsfilter caps=\"video/x-raw,format=BGRx\" !  \
    gvadetect model=$MODEL device=$DEVICE inference-interval=$INFERENCE_INTERVAL ! queue !  \
    gvatrack ! queue ! \
    gvaclassify model=$MODEL2 model-proc=model_proc/vehicle-attributes-recognition-barrier-0039.json device=$DEVICE ! queue !  \
    gvawatermark ! gvafpscounter ! videoconvert ! videoscale ! video/x-raw,width=960,height=540 ! vaapih264enc ! mp4mux ! filesink                 location=$OUTPUT_FILE "

echo "gst-launch-1.0 $PIPELINE"

mkdir -p $(dirname "${OUTPUT_FILE}")
rm "$OUTPUT_FILE"
gst-launch-1.0 $PIPELINE



Yes the environment is functional as I am able to generate output for simple object detection pipeline but not this one.

**Comment by brmarkus** [comment]
By omitting the vaapi-encoding part from the pipeline I get it working:

```
PIPELINE="filesrc location=$INPUT_FILE ! decodebin ! \
videoconvert n-threads=4 ! capsfilter caps="video/x-raw,format=BGRx" ! \
gvadetect model=$MODEL device=$DEVICE inference-interval=$INFERENCE_INTERVAL ! queue ! \
gvatrack ! queue ! \
gvaclassify model=$MODEL2 model-proc=model_proc/vehicle-attributes-recognition-barrier-0039.json device=$DEVICE ! queue ! \
gvawatermark ! gvafpscounter ! videoconvert ! videoscale ! video/x-raw,width=960,height=540 ! xvimagesink sync=true "
```
Can you double-check your installation of the encoder-plugin? Can you maybe use mediasdk-/msdk-/mfx-encoding plugin instead?
Can you check with a simple decoding followed by encoding pipeline like decoding cars.mp4 and encoding it, first? You might not only scale via "video/x-raw,width=960,height=540" but maybe also to a color-space-conversion (e.g. to NV12) depending on the encoder's supported input-formats. (you could dump the raw data into a file first and check with a tool which format it is).

**Comment by sanchitjain04** [comment]
@brmarkus Sure let me check from my end, thank you for your quick help :-)

**Comment by adranit** [comment]
Hi @sanchitjain04,
Is this issue resolved?

**Comment by adranit** [comment]
The issue is closed due to lack of updates for a long time.
