### ISSUE TITLE
Documentation for Face Detection And Classification Python Sample is for another c++ sample

### ISSUE THREAD

**Issue by sscarbal** [opencv/gst-video-analytics#74]
The gst-video-analytics/samples/python/draw_face_attributes/README.md file is supposed to be the documentation of the python implementation for a pipeline of Face Detection And Classification. The documentation is for another c ++ example

**Comment by adranit** [comment]
Hi @sscarbal. Thanks for reporting this error.
Will be fixed in the nearest release.

**Comment by adranit** [comment]
Fixed in 2020.4 (v1.1)
