### ISSUE TITLE
bash: ./samples/gst_launch/face_detection_and_classification/face_detection_and_classification.sh: /bin/bash^M: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by MauryaShraddha** [opencv/gst-video-analytics#75]
I am trying to run the models in the docker on Windows 10. I followed all the steps from the installation guide. When I executed the following command:

`./run_docker_container.sh --video-examples-path=$DATA_PATH/video --intel-models-path=$DATA_PATH/models/intel --models-path=$DATA_PATH/models/common --image-name=gst-video-analytics:latest`

I got the following error:
`./run_docker_container.sh: line 45: xhost: command not found`

I removed the xhost from the run_docker_container.sh file and then followed the procedure and everything worked properly. However, now when I run the command:

`root@default:~/gst-video-analytics# ./samples/gst_launch/face_detection_and_classification/face_detection_and_classification.sh  $VIDEO_EXAMPLES_DIR/face-demographics-walking-and-pause.mp4`

I got the following error:
`bash: ./samples/gst_launch/face_detection_and_classification/face_detection_and_classification.sh: /bin/bash^M: bad interpreter: No such file or directory`

Please help me resolving this issue.

**Comment by brmarkus** [comment]
`/bin/bash^M: bad interpreter: No such file or directory` might be related to line-endings. Have you edited the script `run_docker_container.sh` on your MS-Win machine with an editor changing the line-endings from Linux-line-endings to MS-Win-line-endings?

**Comment by nnshah1** [comment]
**Quick Start for Running on Windows with Docker**

Pre-requisites:
-  Docker for Windows
-  Windows X Server (Moba Xterm is a good option) 


Steps

1. Start XServer on Windows Host 
(Follow instructions from XServer, for example Moba XTerm)

1. Docker Pull: From power shell
   ```
   PS C:\Users\nnshah1> docker pull openvino/ubuntu18_data_dev
   ```

1. Docker Run: From power shell
   ```
   PS C:\Users\nnshah1> docker run -it --rm -ehttps_proxy -ehttp_proxy --network=host --entrypoint /bin/bash --name 
   dlstreamer_test --privileged --user root -openvino/ubuntu18_data_dev
   ```


4. Set Display and no_proxy variable within container and test (note IP will be of host machine such as: 10.212.163.89:0.0)
   ```
   root@docker-desktop:/opt/intel/openvino_2020.3.194# export DISPLAY=HOST_IP_ADDRESS:0.0
   root@docker-desktop:/opt/intel/openvino_2020.3.194# export no_proxy=HOST_IP_ADDRESS
   root@docker-desktop:/opt/intel/openvino_2020.3.194# gst-launch-1.0 videotestsrc ! ximagesink
   ```

5. Install your favorite editor
   
   ```
   root@docker-desktop:/opt/intel/openvino_2020.3.194# apt-get update
   root@docker-desktop:/opt/intel/openvino_2020.3.194# apt-get install emacs
   ```

6. Edit face detection sample to use *ximagesink* instead of *xvimagesink*
    ```
    PIPELINE="gst-launch-1.0 $SOURCE_ELEMENT ! \
     decodebin ! videoconvert ! video/x-raw,format=BGRx ! \
     gvadetect model=$DETECT_MODEL_PATH device=$DEVICE ! queue ! \
     gvaclassify model=$CLASS_MODEL_PATH model-proc=$MODEL2_PROC device=$DEVICE ! queue ! \
     gvaclassify model=$CLASS_MODEL_PATH1 model-proc=$MODEL3_PROC device=$DEVICE ! queue ! \
     gvaclassify model=$CLASS_MODEL_PATH2 model-proc=$MODEL4_PROC device=$DEVICE ! queue ! \
     gvawatermark ! videoconvert ! fpsdisplaysink video-sink=ximagesink sync=false"
    ```
7. Download Models
  ```
  root@docker-desktop:/opt/intel/openvino_2020.3.194# 
  /opt/intel/openvino/data_processing/dl_streamer/samples/download_models.sh
  ```
8.  Run pipeline! 
```
root@docker-desktop:/opt/intel/openvino_2020.3.194# /opt/intel/openvino/data_processing/dl_streamer/samples/gst_launch/face_detection_and_classification/face_detection_and_classification.sh
gst-launch-1.0 urisourcebin buffer-size=4096 uri=https://github.com/intel-iot-devkit/sample-videos/raw/master/head-pose-face-detection-female-and-male.mp4 ! decodebin ! videoconvert ! video/x-raw,format=BGRx ! gvadetect model=/root/intel/dl_streamer/models/intel/face-detection-adas-0001/FP32/face-detection-adas-0001.xml device=CPU ! queue ! gvaclassify model=/root/intel/dl_streamer/models/intel/age-gender-recognition-retail-0013/FP32/age-gender-recognition-retail-0013.xml model-proc=/opt/intel/openvino/data_processing/dl_streamer/samples/gst_launch/face_detection_and_classification/model_proc/age-gender-recognition-retail-0013.json device=CPU ! queue ! gvaclassify model=/root/intel/dl_streamer/models/intel/emotions-recognition-retail-0003/FP32/emotions-recognition-retail-0003.xml model-proc=/opt/intel/openvino/data_processing/dl_streamer/samples/gst_launch/face_detection_and_classification/model_proc/emotions-recognition-retail-0003.json device=CPU ! queue ! gvaclassify model=/root/intel/dl_streamer/models/intel/landmarks-regression-retail-0009/FP32/landmarks-regression-retail-0009.xml model-proc=/opt/intel/openvino/data_processing/dl_streamer/samples/gst_launch/face_detection_and_classification/model_proc/landmarks-regression-retail-0009.json device=CPU ! queue ! gvawatermark ! videoconvert ! fpsdisplaysink video-sink=ximagesink sync=false
```

**Comment by MauryaShraddha** [comment]
Thanks for the help.
When I am trying to run the docker run command, that is, step 3, I get the following error:

`unknown shorthand flag: 'o' in -openvino/ubuntu18_data_dev`

Can you please guide me to resolve this issue?

**Comment by brmarkus** [comment]
Try 
```
PS C:\Users\nnshah1> docker run -it --rm -e https_proxy -e http_proxy --network=host --entrypoint /bin/bash --name 
dlstreamer_test --privileged --user root openvino/ubuntu18_data_dev
```

**Comment by MauryaShraddha** [comment]
Thank you for the response. That worked well!

I am getting the following output after running the pipeline, that is, step 8. 

`Setting pipeline to PAUSED ...
ERROR: Pipeline doesn't want to pause.
ERROR: from element /GstPipeline:pipeline0/GstFPSDisplaySink:fpsdisplaysink0/GstXImageSink:ximagesink0: Could not initialise X output
Additional debug info:
../sys/ximage/ximagesink.c(860): gst_x_image_sink_xcontext_get (): /GstPipeline:pipeline0/GstFPSDisplaySink:fpsdisplaysink0/GstXImageSink:ximagesink0:
Could not open display
Setting pipeline to NULL ...
Freeing pipeline ...`

After reading this, I think this might be related to the step 1 of starting the XServer on Windows host. I installed the Moba XTerm. I am very new to this. Can I please get some guidance on how to perform step 1?

**Comment by brmarkus** [comment]
Is the step #4 working for you?
```
4. Set Display and no_proxy variable within container and test (note IP will be of host machine such as: 10.212.163.89:0.0)
root@docker-desktop:/opt/intel/openvino_2020.3.194# export DISPLAY=HOST_IP_ADDRESS:0.0
root@docker-desktop:/opt/intel/openvino_2020.3.194# export no_proxy=HOST_IP_ADDRESS
root@docker-desktop:/opt/intel/openvino_2020.3.194# gst-launch-1.0 videotestsrc ! ximagesink
```
Have you replaced "HOST_IP_ADDRESS" with the IP-address of your windows machine? Is "gst-launch-1.0 videotestsrc ! ximagesink" working and you see the test-pattern rendered?

**Comment by MauryaShraddha** [comment]
I replaced "HOST_IP_ADDRESS" with the IP-address of my windows machine now and executed the `gst-launch-1.0 videotestsrc ! ximagesink` again. I got the same error.

**Comment by brmarkus** [comment]
So you installed MobaXTerm? You started it, you have a "terminal" open in MobaXTerm? See also "https://mobaxterm.mobatek.net/documentation.html#1_4", which is about "X11 forwarding".
So from within a MobaXTerm terminal you export the DISPLAY and no_proxy variable?
In such a terminal you tried "`gst-launch-1.0 videotestsrc ! ximagesink`"?
Maybe try the "windowed-mode" from MobaXTerm.

**Comment by nnshah1** [comment]
![xserver](https://user-images.githubusercontent.com/15256002/85858431-7a0b4300-b770-11ea-99de-f5659e0b41f1.png)

In the upper right you will see a button "XServer" and you can start the local XServer there

**Comment by nnshah1** [comment]
![prompt](https://user-images.githubusercontent.com/15256002/85858840-23523900-b771-11ea-9620-d12ccf10c24d.png)

When you first run the test command (and when you run the sample) - you will get a pop up to accept the connection to the XServer. (You can also change mobaxterm configuration to avoid this prompt)

**Comment by nnshah1** [comment]
@brmarkus Thanks for fixing the typo in the run command!

**Comment by MauryaShraddha** [comment]
My MobaXterm looks like this:

![image](https://user-images.githubusercontent.com/36510998/85887763-61258080-b7b6-11ea-9346-1d684d932f9f.png)

**Comment by nnshah1** [comment]
that looks right - you'll need just to start the container from power shell, set the display to the ip address of the host, and should work (not the 192. # but the external ip address if you have it)

**Comment by nnshah1** [comment]
(the gst-launch commands should be from inside the container, started via powershell)

**Comment by MauryaShraddha** [comment]
Still getting the same error. Something is going wrong. Can't figure out.

![image](https://user-images.githubusercontent.com/36510998/85904829-b9b94580-b7d7-11ea-87ae-54cce4eefcba.png)

**Comment by nnshah1** [comment]
Try:
```
export DISPLAY=64.121.102.75:0.0
export no_proxy=64.121.102.75
```

**Comment by nnshah1** [comment]
the HOST_IP_ADDRESS should be replaced, not additive there - sorry about that confusion

**Comment by MauryaShraddha** [comment]
Getting the same error:

![image](https://user-images.githubusercontent.com/36510998/85908194-22a5bb00-b7e2-11ea-82d1-2127df44c3e1.png)

What does "Current DISPLAY=192.168.0.49:0.0" mean? Is this error occurring because of the Current Display?

**Comment by nnshah1** [comment]
you can try setting display to 192.168.0.49:0.0 (same for no-proxy) -

**Comment by MauryaShraddha** [comment]
Worked! This looks so great! Thank you so much @nnshah1 and @brmarkus for help. I got to learn a lot. 

![image](https://user-images.githubusercontent.com/36510998/85908918-40c0ea80-b7e5-11ea-84c1-b04e29c61bd2.png)

Is there a way to display this output through MQTT on a Streamlit ?

**Comment by nnshah1** [comment]
Awesome! We support sending the bounding box coordinates (detection results) via mqtt, but not frames themselves. You can see documentation for gvametapublish

**Comment by MauryaShraddha** [comment]
I will check for the details and get back to you. One thing is for sure, OpenVINO is great toolkit to work with, the feature that I loved most about OpenVINO is the way it supports any kind of device (CPU, GPU, and others) and also it's support for multiple operating systems! I would keep exploring OpenVINO and try to come up with some new application of OpenVINO!

**Comment by MauryaShraddha** [comment]
Hello,

Currently the pipeline takes the input as a video from the sample videos. To add to it, I am trying to get the input as live video through my webcamera. I tried the following command:
`/opt/intel/openvino/data_processing/dl_streamer/samples/gst_launch/face_detection_and_classification/face_detection_and_classification.sh /dev/video0`

I get the following output:
`gst-launch-1.0 v4l2src device=/dev/video0 ! decodebin ! videoconvert ! video/x-raw,format=BGRx ! gvadetect model=/root/intel/dl_streamer/models/intel/face-detection-adas-0001/FP32/face-detection-adas-0001.xml device=CPU ! queue ! gvaclassify model=/root/intel/dl_streamer/models/intel/age-gender-recognition-retail-0013/FP32/age-gender-recognition-retail-0013.xml model-proc=/opt/intel/openvino/data_processing/dl_streamer/samples/gst_launch/face_detection_and_classification/model_proc/age-gender-recognition-retail-0013.json device=CPU ! queue ! gvaclassify model=/root/intel/dl_streamer/models/intel/emotions-recognition-retail-0003/FP32/emotions-recognition-retail-0003.xml model-proc=/opt/intel/openvino/data_processing/dl_streamer/samples/gst_launch/face_detection_and_classification/model_proc/emotions-recognition-retail-0003.json device=CPU ! queue ! gvaclassify model=/root/intel/dl_streamer/models/intel/landmarks-regression-retail-0009/FP32/landmarks-regression-retail-0009.xml model-proc=/opt/intel/openvino/data_processing/dl_streamer/samples/gst_launch/face_detection_and_classification/model_proc/landmarks-regression-retail-0009.json device=CPU ! queue ! gvawatermark ! videoconvert ! fpsdisplaysink video-sink=ximagesink sync=false
Setting pipeline to PAUSED ...
ERROR: Pipeline doesn't want to pause.
ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:v4l2src0: This isn't a device '/dev/video0'.
Additional debug info:
../sys/v4l2/v4l2_calls.c(616): gst_v4l2_open (): /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
system error: Resource temporarily unavailable
Setting pipeline to NULL ...
Freeing pipeline ...`

How can I set my input parameter to be webcamera?

**Comment by nnshah1** [comment]
I'm not sure that camera devices can be exposed to docker containers on Windows - but that is possible, you would need to alter the run command to include the correct --device flag. Are you still running in docker on Windows?

**Comment by MauryaShraddha** [comment]
Yes, I am still running in docker on Windows. And also, I altered the docker run command as follows, but not sure whether this is right way.
`docker run -it --rm -e https_proxy -e  http_proxy -v /dev/video0:/dev/video0 --network=host --entrypoint /bin/bash --name dlstreamer_test --privileged --user root openvino/ubuntu18_data_dev`

**Comment by brmarkus** [comment]
Not sure this has been implemented by MS-Win in the meantime (see e.g. here: https://github.com/docker/for-win/issues/2201).
Do you have a chance to convert your USB video camera into an IP video stream, e.g. via VLC or gstreamer?

**Comment by nnshah1** [comment]
I agree with @brmarkus - the most straightforward solution would be to use VLC to restream the usb camera as an rtsp stream -

**Comment by nnshah1** [comment]
@MauryaShraddha  Can I ask you to re-title this issue to "Running DL Streamer in a Docker Container on a Windows host" (or something to that effect)? Also we can potentially close this one and start a new one on how to expose a webcamera to a docker container on a windows host

**Comment by MauryaShraddha** [comment]
@nnshah1  sure. I will close the issue and start a new issue and post my question again. Thank you.
