### ISSUE TITLE
Cannot find dl_streamer folder

### ISSUE THREAD

**Issue by MauryaShraddha** [opencv/gst-video-analytics#76]
Hello,

I have downloaded the latest version of openvino, that is, openvio_2020.3194, on Windows 10 operating system. But I can't find the dl_streamer folder under the data_processing folder. Can someone help me with figuring out whether the installation is wrong or why is the dl_streamer folder missing?

Thank you.

**Comment by brmarkus** [comment]
Can you describe where you got the information about the "dl_streamer folder under data_processing folder" from? Can you reference a documentation, or information from a previous version?

**Comment by nnshah2** [comment]
DL Streamer is only supported on linux operating systems today. The windows binary installer will not install it. To run DL Streamer on Windows - Docker is the only current method.

**Comment by nnshah1** [comment]
DL Streamer is not directly supported on Windows. Current workaround is to run DL Streamer using Docker for Windows.

@brmarkus The OpenVINO binary installer on Linux has the option to install DL Streamer. It will install it under the data processing folder within the /opt/intel/openvino tree.

**Comment by MauryaShraddha** [comment]
@brmarkus I was watching the webniar series by OpenVINO team, specifically the webinar for: Ready, Steady, Stream: Introducing Intel® Distribution of OpenVINO™ toolkit Deep Learning Streamer, in this webinar, I saw there is the folder dl_streamer under the data_processing folder as @nnshah1 mentioned.

Thank you @nnshah1  for the clarification!

**Comment by MauryaShraddha** [comment]
Hello again,

Currently the pipeline takes the input as a video from the sample videos. To add to it, I am trying to get the input as live video through my webcamera. I tried the following command:
`/opt/intel/openvino/data_processing/dl_streamer/samples/gst_launch/face_detection_and_classification/face_detection_and_classification.sh /dev/video0`

I get the following output:
`gst-launch-1.0 v4l2src device=/dev/video0 ! decodebin ! videoconvert ! video/x-raw,format=BGRx ! gvadetect model=/root/intel/dl_streamer/models/intel/face-detection-adas-0001/FP32/face-detection-adas-0001.xml device=CPU ! queue ! gvaclassify model=/root/intel/dl_streamer/models/intel/age-gender-recognition-retail-0013/FP32/age-gender-recognition-retail-0013.xml model-proc=/opt/intel/openvino/data_processing/dl_streamer/samples/gst_launch/face_detection_and_classification/model_proc/age-gender-recognition-retail-0013.json device=CPU ! queue ! gvaclassify model=/root/intel/dl_streamer/models/intel/emotions-recognition-retail-0003/FP32/emotions-recognition-retail-0003.xml model-proc=/opt/intel/openvino/data_processing/dl_streamer/samples/gst_launch/face_detection_and_classification/model_proc/emotions-recognition-retail-0003.json device=CPU ! queue ! gvaclassify model=/root/intel/dl_streamer/models/intel/landmarks-regression-retail-0009/FP32/landmarks-regression-retail-0009.xml model-proc=/opt/intel/openvino/data_processing/dl_streamer/samples/gst_launch/face_detection_and_classification/model_proc/landmarks-regression-retail-0009.json device=CPU ! queue ! gvawatermark ! videoconvert ! fpsdisplaysink video-sink=ximagesink sync=false
Setting pipeline to PAUSED ...
ERROR: Pipeline doesn't want to pause.
ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:v4l2src0: This isn't a device '/dev/video0'.
Additional debug info:
../sys/v4l2/v4l2_calls.c(616): gst_v4l2_open (): /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
system error: Resource temporarily unavailable
Setting pipeline to NULL ...
Freeing pipeline ...`

How can I set my input parameter to be webcamera?

**Comment by nnshah1** [comment]
@MauryaShraddha If this is clear - please close the issue. Thanks!
