### ISSUE TITLE
Fatal Python error: deallocating None

### ISSUE THREAD

**Issue by vtimofeev01** [opencv/gst-video-analytics#77]
By using Python after 14 000 - 30 000 frames got from RTSP it raises that error
GVA is used in Docker container

**Comment by nnshah1** [comment]
This was fixed in a patch release:

https://github.com/opencv/gst-video-analytics/releases/tag/v1.0.1

**Comment by vtimofeev01** [comment]
does this fix us included into docker image "openvino/ubuntu18_runtime:latest" or not?

**Comment by nnshah1** [comment]
I do not believe so - you can check the version though using gst-inspect-1.0, element should indicate 1.0.1 if it has the fix vs 1.0.0 which doesn't.

```
vaserving@nnshah1-NUC8i7BEH:/home/video-analytics-serving$ gst-inspect-1.0 gvadetect
Factory Details:
  Rank                     none (0)
  Long-name                Object detection (generates GstVideoRegionOfInterestMeta)
  Klass                    Video
  Description              Object detection (generates GstVideoRegionOfInterestMeta)
  Author                   Intel Corporation

Plugin Details:
  Name                     videoanalytics
  Description              Video Analytics elements
  Filename                 /opt/intel/openvino/data_processing/dl_streamer/lib/libgstvideoanalytics.so
  Version                  1.0.0.1bc5e376
  License                  MIT/X11
  Source module            gst-video-analytics
  Binary package           GStreamer Video Analytics elements
  Origin URL               https://github.com/opencv/gst-video-analytics

```

**Comment by vtimofeev01** [comment]
Thank U
I m trying to make a new docker image )

**Comment by vtimofeev01** [comment]
I try to compile and make the new Docker image.  
Step 92/128 : COPY l_openvino_toolkit_p_${OpenVINO_VERSION}.tgz . is failed.
the right (2020.2.120) image is in Downloads but is not seen....

**Comment by nnshah1** [comment]
I believe the image (zip) needs to be in the root of the docker build context (root of the cloned repo) -

**Comment by vtimofeev01** [comment]
Thank U
