### ISSUE TITLE
Starting webcamera in docker container on windows host through pipeline

### ISSUE THREAD

**Issue by MauryaShraddha** [opencv/gst-video-analytics#79]
Hello,

Currently the pipeline takes the input as a video from the sample videos. To add to it, I am trying to get the input as live video through my webcamera. I tried the following command:
`/opt/intel/openvino/data_processing/dl_streamer/samples/gst_launch/face_detection_and_classification/face_detection_and_classification.sh /dev/video0`

I get the following output:
`gst-launch-1.0 v4l2src device=/dev/video0 ! decodebin ! videoconvert ! video/x-raw,format=BGRx ! gvadetect model=/root/intel/dl_streamer/models/intel/face-detection-adas-0001/FP32/face-detection-adas-0001.xml device=CPU ! queue ! gvaclassify model=/root/intel/dl_streamer/models/intel/age-gender-recognition-retail-0013/FP32/age-gender-recognition-retail-0013.xml model-proc=/opt/intel/openvino/data_processing/dl_streamer/samples/gst_launch/face_detection_and_classification/model_proc/age-gender-recognition-retail-0013.json device=CPU ! queue ! gvaclassify model=/root/intel/dl_streamer/models/intel/emotions-recognition-retail-0003/FP32/emotions-recognition-retail-0003.xml model-proc=/opt/intel/openvino/data_processing/dl_streamer/samples/gst_launch/face_detection_and_classification/model_proc/emotions-recognition-retail-0003.json device=CPU ! queue ! gvaclassify model=/root/intel/dl_streamer/models/intel/landmarks-regression-retail-0009/FP32/landmarks-regression-retail-0009.xml model-proc=/opt/intel/openvino/data_processing/dl_streamer/samples/gst_launch/face_detection_and_classification/model_proc/landmarks-regression-retail-0009.json device=CPU ! queue ! gvawatermark ! videoconvert ! fpsdisplaysink video-sink=ximagesink sync=false
Setting pipeline to PAUSED ...
ERROR: Pipeline doesn't want to pause.
ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:v4l2src0: This isn't a device '/dev/video0'.
Additional debug info:
../sys/v4l2/v4l2_calls.c(616): gst_v4l2_open (): /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
system error: Resource temporarily unavailable
Setting pipeline to NULL ...
Freeing pipeline ...`

How can I set my input parameter to be webcamera?

**Comment by nnshah1** [comment]
@MauryaShraddha 

Mounting a webcamera into a Linux Docker container on Windows is not directly supported by Docker for Windows so unfortunately there is no simple way to enable your use case. Two options remain to support this:

1) Creating a Virtual Machine (Virtual Box or other), exposing the webcamera to that virtual machine, and then either installing openvino DL Streamer directly or using docker within that virtual machine.

2) Converting your webcamera to an IP camera and streaming over the network to your docker container

In general DLStreamer doesn't support Windows directly and these techniques are only to enable early development / prototyping on Windows. 

OpenVINO on the other hand in general does support Windows and some of the other non DL Streamer based tutorials can be made to work with web cameras via opencv.

**Comment by MauryaShraddha** [comment]
@nnshah1 Thank you. I will try to work on this and check if any simple way can be made to resolve this.

**Comment by nnshah1** [comment]
@MauryaShraddha - One of my colleagues may have a solution - I will also check if we can provide some simple instructions via virtual box

**Comment by MauryaShraddha** [comment]
@nnshah1 Thank you so much. This means a lot and is really helpful. I will keep working on this and let you know if I get a breakthrough.

**Comment by nnshah1** [comment]
No problem, adding @tobiasmo1, as he may be able to help.

**Comment by tobiasmo1** [comment]
@MauryaShraddha - With [VirtualBox](https://www.virtualbox.org/wiki/Downloads) set up to run a Ubuntu 18.04 VM, it is reasonably straightforward to configure a pipeline to access your host's webcam.  You will need to add an Ubuntu .iso as a disk, install GuestAdditions with sufficient disk space (recommend dynamic 50GB). Install latest docker on that Guest host and then with the VM powered off, you'll select the camera from the VM's (Settings -> USB) dropdown - which reserves the camera on behalf of the VM (prevents Windows from locking it).

I recommend then confirming /dev/video0 is available to the VM by installing Cheese:
$ **sudo apt-get install cheese**
$ **cheese**

Once that is verified, the webcam will be accessible as /dev/video0 in the DL Streamer docker container.
