### ISSUE TITLE
Is there a how to for using my open opencv app with gst-video-analytics?

### ISSUE THREAD

**Issue by js07920** [opencv/gst-video-analytics#8]

**Comment by alalek** [comment]
OpenCV's VideoCapture interface doesn't cover capabilities of this project.

You should use GStreamer framework directly.

**Comment by js07920** [comment]
Is there a "hello world"/simplest C/C++ app I can use as basis?

**Comment by alalek** [comment]
Here: https://github.com/opencv/gst-video-analytics/tree/master/samples/cpp

**Comment by Andruxin52rus** [comment]
@alalek Thanks for help with this one! @js07920 if it's still not feasible for you how to use GVA plugin from C/C++ side, please open a new issue
