### ISSUE TITLE
Install on host machine->  Build GVA plugin

### ISSUE THREAD

**Issue by kqchen** [opencv/gst-video-analytics#80]
cmake ..

......
CMake Error at gst/elements/CMakeLists.txt:52 (add_library):
  Target "elements" links to target "IE::inference_engine_legacy" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

CMake Error at gst/inference_elements/CMakeLists.txt:35 (add_library):
  Target "inference_elements" links to target "IE::inference_engine_legacy"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?

CMake Error at gst/registrator/CMakeLists.txt:21 (add_library):
  Target "gstvideoanalytics" links to target "IE::inference_engine_legacy"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?

CMake Error at inference_backend/image_inference/openvino/CMakeLists.txt:23 (add_library):
  Target "image_inference_openvino" links to target
  "IE::inference_engine_legacy" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?

**Comment by brmarkus** [comment]
Did you try to build GVA only (by calling "cmake .." in the GVA folder) or tried to build OpenCV including GVA? Can you describe your folder-structure, please?
GVA either needs OpenVINO to be installed via the pre-built OpenVINO installation package (from software.intel.com) or that you build the OpenCV's DNN/InferenceEngine (first or in addition).

**Comment by adranit** [comment]
Hi @kqchen,
I assume you built OpenVINO IE from sources on GitHub. Am I right? If yes what version of IE did you use?

**Comment by kqchen** [comment]
@: brmarkus
I am a CW working with Intel IOTG. I try to make gst based demo/exercise 1/exercise 2  working before I move on a customer project.
https://github.com/opencv/gst-video-analytics/wiki/GStreamer%20Video%20Analytics%20Tutorial#section-2-exercise-1-build-simple-pipelines-

I downloaded OpenVino toolkit   2020.1.023 on Linux 18.04 with a IOT tank machine. Here is what I got.
''' ******************************* 
I try to build the GVA plugin following those steps under:
2.2. Install on host machine (https://github.com/opencv/gst-video-analytics/wiki/Install-Guide#22-install-on-host-machine-)
tank-18@tank18:~/gva/gst-video-analytics/build$ cmake ..
-- CMAKE_BUILD_TYPE is undefined. Set default build type Release.
CMake Warning at CMakeLists.txt:25 (message):
  VERSION_PATCH is undefined.  Set default value 0.

CMake Warning at CMakeLists.txt:30 (message):
  GIT_INFO is undefined.  Set default value 0.

ENABLE_PAHO_INSTALLATION=OFF
ENABLE_RDKAFKA_INSTALLATION=OFF
MQTT support will not be available. Ensure required libraries (Paho MQTT) are installed, and rebuild plugin with -DMQTT=1 before attempting to use MQTT
Kafka support will not be available. Ensure required libraries (librdkafka) are installed, and rebuild plugin with -DKAFKA=1 before attempting to use Kafka
-- Checking for module 'pygobject-3.0'
--   No package 'pygobject-3.0' found
-- Found OpenCV: /opt/intel/openvino_2020.1.023/opencv (found version "4.2.0") found components:  core imgproc imgcodecs 
-- Found OpenCV: /opt/intel/openvino_2020.1.023/opencv (found version "4.2.0") found components:  core imgproc 
-- Configuring done
CMake Error at gst/elements/CMakeLists.txt:52 (add_library):
  Target "elements" links to target "IE::inference_engine_legacy" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

CMake Error at gst/inference_elements/CMakeLists.txt:35 (add_library):
  Target "inference_elements" links to target "IE::inference_engine_legacy"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?

CMake Error at gst/registrator/CMakeLists.txt:21 (add_library):
  Target "gstvideoanalytics" links to target "IE::inference_engine_legacy"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?

CMake Error at inference_backend/image_inference/openvino/CMakeLists.txt:23 (add_library):
  Target "image_inference_openvino" links to target
  "IE::inference_engine_legacy" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?

-- Generating done
-- Build files have been written to: /home/tank-18/gva/gst-video-analytics/build

**Comment by kqchen** [comment]
@adranit 
I downloaded openvino_2020.1.023, and installed it under /opt/intel/openvino
I am not sure about the IE version.

**Comment by kqchen** [comment]
@brmarkus 
I try to build GVA only. Here is the folder structure:

tank-18@tank18:~/gva/gst-video-analytics$ ls
build           docker    inference_backend  python     thirdparty
cmake           docs      intro.gif          README.md  third-party-programs
CMakeLists.txt  gst       LICENSE            samples
CODESTYLE.md    gst-libs  patches            scripts

**Comment by adranit** [comment]
@kqchen,
Sorry for the late response. I recommend to use the latest version of GVA(v1.1) and OpenVino (2020.4). 
The previous version of GVA (v1.0) is compatible with OV2020.3 and OV2020.2. If you need to use OV2020.1 then you should use the appropriate version of GVA - v0.7.
Please find the list of versions here: https://github.com/opencv/gst-video-analytics/releases

**Comment by easychizy** [comment]
Hi @kqchen 

Thanks for using our product and help us to improve.

Back to your original question, did your problem resolved by our information?

Mark

**Comment by kqchen** [comment]
I am not pursue this build issue at this point. We can close this issue.
