### ISSUE TITLE
using gvatrack

### ISSUE THREAD

**Issue by Pked01** [opencv/gst-video-analytics#81]
hello
I am new to gst-video-analytics..
I was trying vehicle tracking example  but got following error

Setting pipeline to PAUSED ...
__Pipeline is PREROLLING ...
G_ot context from element 'vaapipostproc0': gst.vaapi.Display=context, gst.vaapi.Display=(GstVaapiDisplay)"\(GstVaapiDisplayGLX\)\ vaapidisplayglx0";
Redistribute latency...
WARNING: from element /GstPipeline:pipeline0/GstDecodeBin:decodebin0: Delayed linking failed.
Additional debug info:
../gst/parse/grammar.y(510): gst_parse_no_more_pads (): /GstPipeline:pipeline0/GstDecodeBin:decodebin0:
failed delayed linking some pad of GstDecodeBin named decodebin0 to some pad of GstVideoConvert named videoconvert0
ERROR: from element /GstPipeline:pipeline0/GstDecodeBin:decodebin0/GstVaapiDecodeBin:vaapidecodebin0/GstQueue:vaapi-queue: Internal data stream error.
Additional debug info:
../plugins/elements/gstqueue.c(988): gst_queue_handle_sink_event (): /GstPipeline:pipeline0/GstDecodeBin:decodebin0/GstVaapiDecodeBin:vaapidecodebin0/GstQueue:vaapi-queue:
streaming stopped, reason not-linked (-1)
ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
Freeing pipeline ...

I used this command: 

gst-launch-1.0 \
    filesrc location=${VIDEO_EXAMPLE} ! decodebin ! video/x-raw ! videoconvert ! \
    gvadetect model=${DETECTION_MODEL} model_proc=${DETECTION_MODEL_PROC} device=GPU inference-interval=10 ! queue ! \
    gvatrack tracking-type=short-term ! queue ! \
    gvaclassify model=${VEHICLE_CLASSIFICATION_MODEL} model-proc=${VEHICLE_CLASSIFICATION_MODEL_PROC} device=CPU object-class=vehicle reclassify-interval=10 ! queue ! \
    gvawatermark ! fpsdisplaysink video-sink=xvimagesink sync=false

Again if i remove gvatrack pipeline works normally,Can you please help me with this issue

**Comment by brmarkus** [comment]
Is the script `vehicle_pedestrian_tracking.sh` under "https://github.com/opencv/gst-video-analytics/tree/master/samples/gst_launch/vehicle_pedestrian_tracking" working for you?

**Comment by Pked01** [comment]
yes , this sample is working for me, 
thanks for reference, i will try to generate command as per the example.
