### ISSUE TITLE
what is correct way to use multiple streams

### ISSUE THREAD

**Issue by Pked01** [opencv/gst-video-analytics#82]
hello 
I want to run gva with on multiple input feeds,
one simple way is to 
**gst-launch-1.0 {pipeline1}  {pipeline-2)**

where each pipeline is od this format    

_filesrc location=${VIDEO_EXAMPLE} ! decodebin ! videoconvert ! video/x-raw,format=BGRx ! videoconvert ! \
    gvadetect model=${DETECTION_MODEL} model_proc=${DETECTION_MODEL_PROC} device=CPU threshold=.4 inference-interval=10 ! queue ! \
    gvatrack tracking-type=short-term ! queue ! \
    gvaclassify model=${VEHICLE_CLASSIFICATION_MODEL} model-proc=${VEHICLE_CLASSIFICATION_MODEL_PROC} device=CPU object-class=vehicle reclassify-interval=10 device=CPU ! queue ! \
    gvawatermark ! videoconvert ! fpsdisplaysink video-sink=xvimagesink sync=true_

is this right way?
if yes does model resources get between pipelines?

**Comment by kkoryun** [comment]
Hello 

Yes , this is the normal way. If you want to share the inference backend in between few inference elements you can use property: **model-instance-id**.


gst-launch-1.0 filesrc location= ! decodebin ! videoconvert ! video/x-raw,format=BGRx ! videoconvert ! gvadetect **model-instance-id=dtc** \<other property\>  ! gvaclassify **model-instance-id=cls** \<other property\> ! fakesink   filesrc location= ! decodebin ! videoconvert ! video/x-raw,format=BGRx ! videoconvert ! gvadetect **model-instance-id=dtc**  \<other property\> ! gvaclassify **model-instance-id=cls** \<other property\> ! fakesink 

<img width="470" alt="Screenshot 2020-07-14 at 17 42 14" src="https://user-images.githubusercontent.com/14761166/87439414-6fb6c900-c5f9-11ea-87d5-61b9f3beb803.png">

Note that sharing resources between other elements is not guaranteed: for example, your decoder or image processor may not share resources.

**Comment by easychizy** [comment]
Hi @Pked01 ,

Do you think @kkoryun answered your question?

If yes, we will close this but feel free if you have more questions.

Mark

**Comment by Deepak3994** [comment]
Hi,

I am using GStreamer Webrtcbin with sendrecv, may I know how we have multiple camera input added in single pipeline which i can send to webrowser.

Any lead will be helpful.
Thank you.

**Comment by brmarkus** [comment]
@Deepak3994 this issue is in CLOSED state, please create a new issue for your question. Have you found an answer in the meantime?
