### ISSUE TITLE
NVIDIA Support

### ISSUE THREAD

**Issue by Surya059** [opencv/gst-video-analytics#83]
Hi, 

I see that the whole pipeline is quite modularized. Can this repository also support NVIDIA devices upon some modifications..
For Example:
Adding something like **gst-video-analytics/inference_backend/image_inference/TensorRT/** in place of 
**gst-video-analytics/inference_backend/image_inference/openvino/** 

Could you also list down the changes that need to be made and also the dependencies on OpenVINO?

**Comment by Surya059** [comment]
Hi, Could you please close this issue If it is not relevant?

**Comment by easychizy** [comment]
Hi @Surya059,

Sorry for the late response, DL Streamer is the GStreamer element for OpenVINO, so I think your question is actually, can OpenVINO support TensorRT? 
As you know OpenVINO requires a IR format to support models on Intel platform, I think Nvidia has the same requirement although they have their model format.
Does this answers your question?
Mark

**Comment by intel-neena** [comment]
@Surya059 OpenVINO and DL Streamer are highly optimized for Intel devices - CPU, GPU, VPU. We do not have NVIDIA support on our roadmap at this time.

**Comment by Surya059** [comment]
> Hi @Surya059,
> 
> Sorry for the late response, DL Streamer is the GStreamer element for OpenVINO, so I think your question is actually, can OpenVINO support TensorRT?
> As you know OpenVINO requires a IR format to support models on Intel platform, I think Nvidia has the same requirement although they have their model format.
> Does this answers your question?
> Mark

Hi, thanks for responding. I see that there is no dependency on OpenVINO atleast for inference plugin wrapper. inference backend code is seperated from gvainference. I don't see any problem using a different inference backend (tensorRT). Am I missing something here?

**Comment by intel-neena** [comment]
@Surya059 Since we have not tried other inference backends, I can't be sure of all the challenges. You may try and let us know.
