### ISSUE TITLE
Running sample in docker fails

### ISSUE THREAD

**Issue by js07920** [opencv/gst-video-analytics#9]
```
root@up2:~/gstreamer-plugins# ./samples/shell/face_detection_and_classification.sh /root/video-examples/input.avi
[setup_env.sh] GStreamer-plugins environment initialized
Running sample with the following parameters:
GST_PLUGIN_PATH=/usr/lib/va-gstreamer-plugins/
LD_LIBRARY_PATH=
Setting pipeline to PAUSED ...
ERROR: Pipeline doesn't want to pause.
Got context from element 'fps-display-video_sink-actual-sink-vaapi': gst.vaapi.Display=context, gst.vaapi.Display=(GstVaapiDisplay)"\(GstVaapiDisplayGLX\)\ vaapidisplayglx1";
ERROR: from element /GstPipeline:pipeline0/GstGvaInference:gvainference0: gvainference plugin intitialization failed
Additional debug info:
/root/gstreamer-plugins/gst/elements/gvainference/gstgvainference.c(452): gst_gva_inference_start (): /GstPipeline:pipeline0/GstGvaInference:gvainference0:
Incorrect number of input edges for layer mbox_conf_reshape
/opt/intel/dldt/inference-engine/include/details/ie_exception_conversion.hpp:71
Setting pipeline to NULL ...
Freeing pipeline ...
root@up2:~/gstreamer-plugins# 

```

**Comment by umed** [comment]
hi @js07920 ,

did you run below command before running docker container?

```sh
xhost +
```

**Comment by vijnasu** [comment]
xhost is done, but the same error is recurring in latest version..

./samples/shell/face_detection_and_classification.sh $VIDEO_EXAMPLES_DIR/face-demographics-walking-and-pause.mp4
[setup_env.sh] GStreamer-plugins environment initialized
[setlocale.sh] C locale is set
Running sample with the following parameters:
GST_PLUGIN_PATH=/root/gstreamer-plugins/scripts/../build/intel64/Release/lib:/usr/lib/va-gstreamer-plugins/
LD_LIBRARY_PATH=
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
Setting pipeline to PAUSED ...
ERROR: Pipeline doesn't want to pause.
ERROR: from element /GstPipeline:pipeline0/GstFPSDisplaySink:fpsdisplaysink0/GstXvImageSink:xvimagesink0: Could not initialise Xv output
Additional debug info:
xvimagesink.c(1773): gst_xv_image_sink_open (): /GstPipeline:pipeline0/GstFPSDisplaySink:fpsdisplaysink0/GstXvImageSink:xvimagesink0:
XVideo extension is not available
Setting pipeline to NULL ...
Freeing pipeline ...
