### ISSUE TITLE
Mounting local files and directories onto the dlstreamer_test container 

### ISSUE THREAD

**Issue by MauryaShraddha** [opencv/gst-video-analytics#91]
Hello,

I am trying to mount a directory present on my machine into the docker container: dlstreamer_test, on Windows 10 OS. I referred the tutorial available at: https://www.youtube.com/watch?v=ht4gqt4zSyw to achieve this. 

I used the following command: 
`docker cp C:/Users/ShraddhaM/OneDrive/Desktop/streamlit-docker-master dlstreamer_test:/opt/intel/openvino_2020.3.194/streamlit-docker-master`

I also tried this command: 
`docker cp C:/Users/ShraddhaM/OneDrive/Desktop/streamlit-docker-master dlstreamer_test:/openvino/ubuntu18_data_dev/streamlit-docker-master`

I getting the following errors respectively,  for both commands:
`Error: No such container:path: dlstreamer_test:\opt\intel\openvino_2020.3.194`
`Error: No such container:path: dlstreamer_test:\openvino\ubuntu18_data_dev`

@nnshah1 @brmarkus Can you please guide me to resolve this?

**Comment by brmarkus** [comment]
Sorry, I don't use Docker under MS-Win (yet), only under Linux environments.

Under Linux I use command lines like this:

docker run -it -v /outside/folder1/:/inside/folder1/ -v /outside/writable/:/inside/writable/:rw mycontainer:1.2.3 /bin/bash

=> "mapping" two volumes, the host folder /outside/folder1/ will be available inside the container as /inside/folder1/, and another one where I specify that I want to write/change/add something from within the container.

**Comment by MauryaShraddha** [comment]
@brmarkus  Thank you for the solution.
