### ISSUE TITLE
Encountered an error while execute metapublish.sh

### ISSUE THREAD

**Issue by nowaylin** [opencv/gst-video-analytics#92]
Hi~Team

Good Day

I just want to pass the inference data to EdgeX via mqtt while using webcam as an incoming video source , so I clone the 

header form git hub , and after into gst-video-analytics docker , I follow the demonstrate by this website

(https://docs.openvinotoolkit.org/latest/gst_samples_gst_launch_metapublish_README.html)

and type  $ ./metapublish.sh /dev/video0 mqtt localhost:1883 AnalyticsData

then we got something error response as shown below

![image](https://user-images.githubusercontent.com/67246971/88357150-d9269c80-cd9c-11ea-8bd2-0e64b6c24d33.png)

and I'm sure the webcam driver works very well

![image](https://user-images.githubusercontent.com/67246971/88357217-18ed8400-cd9d-11ea-8a86-42cf626dc2e2.png)

so , Is there anything else I need to pay attention to ??

by the way , I using VMware 15 and Ubuntu 18.04.4 over testing

![image](https://user-images.githubusercontent.com/67246971/88357369-9913e980-cd9d-11ea-82ec-23280a033ca2.png)

BR
Noway

**Comment by nnshah1** [comment]
@nowaylin 

In addition to the DLStreamer elements we also have a reference uService called Video Analytics Serving which demonstrates how to use DL Streamer pipelines to send inferences to Edge-X via the MQTT device service. You can find more details via the Edge Software Hub

https://software.intel.com/content/www/us/en/develop/topics/iot/edge-solutions/retail-recipes.html

In regards to your original issue - we will have to look deeper. Just to confirm: you are running DL Streamer within a Ubuntu VM? Is the host OS windows or Linux? 

It also looks as if you have built DLStreamer without mqtt support (you will need to enable it via CMAKE flags).

https://github.com/opencv/gst-video-analytics/wiki/Getting-Started-Guide-%5B2020.1%5D#install-message-brokers-optional

What version of opencv is installed in the system? That seems to be the root of the first issue with regards libvasot.so

**Comment by nowaylin** [comment]
@nnshah1 

Thanks for you quickly reply , about what you are asking , the reply as below 

"you are running DL Streamer within a Ubuntu VM? Is the host OS windows or Linux?"
=> **Yes , the host OS is Win10**

"What version of opencv is installed in the system? That seems to be the root of the first issue with regards libvasot.so"
=> **How do I check what the Opencv version is it??**

"In addition to the DLStreamer elements we also have a reference uService called Video Analytics Serving which demonstrates how to use DL Streamer pipelines to send inferences to Edge-X via the MQTT device service. You can find more details via the Edge Software Hub"
=> **In fact , there are some issues and I also posted a similarly question on Edge Insights of Retail forum (links : https://community.intel.com/t5/Intel-Edge-Software-Hub/How-to-change-the-video-source-through-webcam-in-Edge-Insights/m-p/1191811#M59 ) when I using VAS via RESTful API to do the same thing , so I just want to narrow down the question to use gst-launch-1.0 command to check the issue.** 


In here , I write down the detail step before I run GVA docker , It might be more clearly the current environment what I running right now. (ref link : https://github.com/opencv/gst-video-analytics/wiki/Install-Guide)

1. Install in Docker image 
![image](https://user-images.githubusercontent.com/67246971/88364403-6118a080-cdb5-11ea-814d-4ed3628dc194.png)
    and build OpenVINO with opensource 
![image](https://user-images.githubusercontent.com/67246971/88364497-ad63e080-cdb5-11ea-8327-6466fbd6fd58.png)

2. After build was completed  , Run docker image with command 
![image](https://user-images.githubusercontent.com/67246971/88364735-717d4b00-cdb6-11ea-8699-7ea9f3c2931f.png)
In order to use webcam as video source , I type the command as below
![image](https://user-images.githubusercontent.com/67246971/88364824-bf924e80-cdb6-11ea-8055-f3d544b75ed4.png)

3. final step , into metapublish file to excute the metapublish.sh

Many thanks 

BR 
Noway Lin

**Comment by nnshah1** [comment]
Thanks Noway Lin! I've responded on the Edge Insights forum - in general there shouldn't be an issue in getting that to work - and that might be a faster path altogether.

You'll need to start the VA Serving docker with volume mount to the device (just as for the gva docker) - and send the right command. We have examples of  this (using with a webcam) - but need to get the log to understand the VA Serving version you are using.

**Comment by nowaylin** [comment]
@nnshah1 

Thanks for the strongly support!!

And now , I will close this issue and move to the Edge Insights of Retail forum to keep going this thread

Many thanks 

BR
Noway Lin
