### ISSUE TITLE
Running GVA on VNC 

### ISSUE THREAD

**Issue by ravikumarbhattiprolu** [opencv/gst-video-analytics#93]
All,
I have a machine with i7-8656u with Ubuntu 18.04LTS and it is inside a lab with no monitor. So, I am running VNC
(vnc4server) to connect to it. I am trying to run gstreamer video analytics example. I have followed all the steps and installed all the dependencies. When I try to run first sample,  It fails at xvimagesink. So, when I do "xvinfo" I get:
X-Video Extension version 2.2
screen #0
 no adaptors present

I guess this is because VNC uses virtual display. To test this I do:
"gst-launch-1.0 videotestsrc ! videoconvert ! autovideosink"

It shows test video and works fine. When I setup required environmental variables for GVA, the same command crashes. Further debug shows, the environment variable GST_VAAPI_ALL_DRIVERS is making difference. When it is unset, autovideosink seem to pickup kmssink and when GST_VAAPI_ALL_DRIVERS is set, it seems to pickup vaapisink and that is causing crash.

I set "WAYLAND_DISPLAY" to reduce the rank of vaapisink. Then test stream works fine. 

Now I am having issues running GVA:
gst-launch-1.0 filesrc location="${VIDEO_DIR}/test.mp4" ! decodebin ! video/x-raw ! videoconvert !  gvadetect model=${DETECTION_MODEL} model_proc=${DETECTION_MODEL_PROC} device=CPU ! queue !  gvawatermark ! autovideosink

and then get errors:
Setting pipeline to PAUSED ...
drmOpenDevice: node name is /dev/dri/card0
drmOpenDevice: open result is 9, (OK)
drmGetBusid returned ''
Pipeline is PREROLLING ...
Got context from element 'vaapipostproc0': gst.vaapi.Display=context, gst.vaapi.Display=(GstVaapiDisplay)"\(GstVaapiDisplayGLX\)\ vaapidisplayglx0";
Redistribute latency...
WARNING: from element /GstPipeline:pipeline0/GstDecodeBin:decodebin0: Delayed linking failed.
Additional debug info:
../gst/parse/grammar.y(510): gst_parse_no_more_pads (): /GstPipeline:pipeline0/GstDecodeBin:decodebin0:
failed delayed linking some pad of GstDecodeBin named decodebin0 to some pad of GstVideoConvert named videoconvert0

ERROR: from element /GstPipeline:pipeline0/GstDecodeBin:decodebin0/GstVaapiDecodeBin:vaapidecodebin0/GstQueue:vaapi-queue: Internal data stream error.
Additional debug info:
../plugins/elements/gstqueue.c(988): gst_queue_handle_sink_event (): /GstPipeline:pipeline0/GstDecodeBin:decodebin0/GstVaapiDecodeBin:vaapidecodebin0/GstQueue:vaapi-queue:
streaming stopped, reason not-linked (-1)
ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
Freeing pipeline ...

Any pointers to get over this will help me progress.

thanks and regards,
Ravi

**Comment by nnshah1** [comment]
If you're not specific to using vaapi - can you try 

`ximagesink` instead of `xvimagesink` ?

**Comment by ravikumarbhattiprolu** [comment]
Thanks Neelay. I am able to run the examples over VNC using ximagesink. However, I needed to add extra "videoconvert' pipeline stage before ximagesink. For example:

gst-launch-1.0 filesrc location=cut.mp4 ! decodebin ! gvadetect model=face-detection-adas-0001.xml ! gvaclassify model=emotions-recognition-retail-0003.xml model-proc=emotions-recognition-retail-0003.json ! gvawatermark ! xvimagesink sync=false 
needs to be modified as:
gst-launch-1.0 filesrc location=cut.mp4 ! decodebin ! gvadetect model=face-detection-adas-0001.xml ! gvaclassify model=emotions-recognition-retail-0003.xml model-proc=emotions-recognition-retail-0003.json ! gvawatermark ! videoconvert ! xvimagesink sync=false

regards,
Ravi

**Comment by nnshah1** [comment]
Thanks for the confirmation Ravi!

Enabling remote accelerated display (ie through VAAPI)  is tricky and from my understanding requires additional setup in VNC and your X Server. So running over VNC with ximagesink will allow you to develop and debug but will be suboptimal in terms of performance. 

Minor typo in your comment - xvimagesink -> ximagesink. If you edit the post so others can see the final pipeline.

If this resolves your current issue - please close it. If you need to enable accelerated remote rendering - please open a new issue with title / description to match.
