### ISSUE TITLE
gvadetect model_proc

### ISSUE THREAD

**Issue by zizo1111** [opencv/gst-video-analytics#96]
Hi, 

I have a YOLOv3 model trained to detect 5 classes, I have converted the model, and tried to run inference using gvadetect, I have created the model_proc JSON file similar to the examples, but it seems like the non-max-suppression step, or something the post processing does not get executed since i have bounding boxes all over the image. 
I have tried some of the models from the model zoo like the "person-vehicle-bike-detection-crossroad-0078" and it works fine.

The pipeline:
gst-launch-1.0 -v --gst-plugin-path ${GST_PLUGIN_PATH} \
                filesrc location=${VIDEO_EXAMPLE} ! decodebin ! video/x-raw ! videoconvert ! \
                gvadetect model-instance-id=inf0 model=${model_path} device=CPU model_proc=${proc_path} ! queue ! \
                gvawatermark ! videoconvert ! autovideosink \

The model_proc JSON file:
`{
    "json_schema_version": "2.0.0",
    "input_preproc": [],
    "output_postproc": [
      {
        "converter": "tensor_to_bbox_yolo_v3",
        "layer_name": "detector/yolo-v3/Conv_6/BiasAdd/YoloRegion",
        "iou_threshold": 0.5,
        "classes": 5,
        "anchors": [
          12.0,
          16.0,
          18.0,
          20.0,
          26.0,
          33.0,
          32.0,
          23.0,
          43.0,
          45.0,
          46.0,
          30.0,
          67.0,
          49.0,
          90.0,
          69.0,
          119.0,
          105.0
        ],
        "masks": [
          6,
          7,
          8,
          3,
          4,
          5,
          0,
          1,
          2
        ],
        "bbox_number_on_cell": 3,
        "labels": [
          "background",
          "Car",
          "Pedestrian",
          "Truck",
          "cyclist"
        ]
      }
    ]
  }`

The output looks like this:

![gst-video](https://user-images.githubusercontent.com/51127805/89428359-98d00280-d73c-11ea-9f70-28605e34fd49.png)
![gst-video1](https://user-images.githubusercontent.com/51127805/89428368-9a99c600-d73c-11ea-8d8c-567f0488ba0a.png)

System Ubuntu 18.04
openvino 2020.4.287 

Thanks!

**Comment by dsmertin** [comment]
@zizo1111 Hello!
Can you please to share your IE (.xml + .bin) models with us?
And tell me, what instructions did you use to convert it and what format was the original model (TF, Pytorch or something else)?

**Comment by dsmertin** [comment]
> "labels": [ "background", "Car", "Pedestrian", "Truck", "cyclist" ]

It's worth trying to remove `" background "` from the list.

**Comment by zizo1111** [comment]
Hello, thanks for the reply. I reinstalled openvino and rebuilt the gst plugins again, and it seems now to work. :)
