### ISSUE TITLE
OpenVino Security demo model "license-plate-recognition-barrier-0001" not working in container with gvaclassify

### ISSUE THREAD

**Issue by kqchen** [opencv/gst-video-analytics#98]
root@tank18:~# gst-launch-1.0 filesrc location=$VIDEO_EXAMPLES_DIR/Shanghai_Traffic_1m12s.mp4 ! decodebin ! video/x-raw ! videoconvert ! gvadetect model=/root/intel_models/vehicle-license-plate-detection-barrier-0106/FP32/vehicle-license-plate-detection-barrier-0106.xml !  queue ! gvaclassify model=/root/intel_models/license-plate-recognition-barrier-0001/FP32/license-plate-recognition-barrier-0001.xml device=CPU ! queue ! gvawatermark ! fpsdisplaysink video-sink=xvimagesink sync=false
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Got context from element 'vaapipostproc0': gst.vaapi.Display=context, gst.vaapi.Display=(GstVaapiDisplay)"\(GstVaapiDisplayGLX\)\ vaapidisplayglx0";
Redistribute latency...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Got EOS from element "pipeline0".
Execution ended after 0:00:13.697006145
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...

**Comment by kqchen** [comment]
Run this on a IOT tank with ubuntu 18.04 as shown above.
https://docs.openvinotoolkit.org/2019_R1/_license_plate_recognition_barrier_0001_description_license_plate_recognition_barrier_0001.html

"gvadetect model=/root/intel_models/vehicle-license-plate-detection-barrier-0106" is working as a black rectangle around the plate can be seen. However,
"gvaclassify model=/root/intel_models/license-plate-recognition-barrier-0001" not working as license plate is not shown

**Comment by adranit** [comment]
Hi @kqchen ,

This model requires the model_proc file - "[license-plate-recognition-barrier-0001.json](https://github.com/opencv/gst-video-analytics/blob/master/samples/model_proc/license-plate-recognition-barrier-0001.json)".

gvaclassify model=/root/intel_models/license-plate-recognition-barrier-0001/FP32/license-plate-recognition-barrier-0001.xml **model-proc=license-plate-recognition-barrier-0001.json** device=CPU

**Comment by adranit** [comment]
gst-launch-1.0 filesrc location=$VIDEO_EXAMPLES_DIR/Shanghai_Traffic_1m12s.mp4 ! decodebin ! video/x-raw ! videoconvert ! gvadetect model=/root/intel_models/vehicle-license-plate-detection-barrier-0106/FP32/vehicle-license-plate-detection-barrier-0106.xml **model-proc=vehicle-license-plate-detection-barrier-0106.json** ! queue ! gvaclassify model=/root/intel_models/license-plate-recognition-barrier-0001/FP32/license-plate-recognition-barrier-0001.xml **model-proc=license-plate-recognition-barrier-0001.json** device=CPU **object-class=license-plate** ! queue ! gvawatermark ! fpsdisplaysink video-sink=xvimagesink sync=false

Try to use model_proc files for gvadetect and gvaclassify. Also specify object-class for license-plate-recognition-barrier-0001 model.
This pipeline must work fine.

**Comment by kqchen** [comment]
Ok, thanks. I will give it a try and let you all know.

**Comment by kqchen** [comment]
Yes, that worked with model-proc.
However, it did not take in the EIS framwork:
```
 "/VideoIngestion/config": {
        "encoding": {
            "type": "jpeg",
            "level": 96
        },
        "ingestor": {
            "type": "gstreamer",
            "pipeline": "multifilesrc loop=TRUE location=./test_videos/Shanghai_Traffic_1m12s.avi ! h264parse ! decodebin ! videoconvert ! video/x-raw,format=BGR ! gvadetect model=models/vehicle-license-plate-detection-barrier-0106.xml model-proc=modles/vehicle-license-plate-detection-barrier-0106.json queue ! gvaclassify model=models/license-plate-recognition-barrier-0001.xml model-proc=modles/license-plate-recognition-barrier-0001.json device=CPU ! appsink"
        }
    },

Logging (IEdgeInsights/docker_setup$ sudo docker logs -f ia_video_ingestion) gave me error like this:
"[Tue Aug 11 16:14:08 2020] ERROR:bus_call:189: Gst Bus Error: base_inference plugin intitialization failed"

**Comment by kqchen** [comment]
No worry, this ingestor config got me the meta data and video. I will continue to test.
        "ingestor": {

            "type": "gstreamer",
            "pipeline": "multifilesrc loop=TRUE location=./test_videos/Shanghai_Traffic_1m12s.avi ! h264parse ! decodebin ! videoconvert ! video/x-raw,format=BGR ! gvadetect model=models/vehicle-license-plate-detection-barrier-0106.xml model-proc=models/vehicle-license-plate-detection-barrier-0106.json ! queue ! gvaclassify model=models/license-plate-recognition-barrier-0001.xml model-proc=models/license-plate-recognition-barrier-0001.json device=CPU ! appsink"
        }

**Comment by kqchen** [comment]
While the docker run above seems worked right (license plate was recognized in the mode/model-porc) with this pipeline setup
But the EIS ia_visualizer only display "0" for all different license plates. 

// the gva_meta definitely indicate the license-plate-recognition-barrier-0001.xml did recognition work, I think, however the a_visulizer display "0" on top of the plate rectangle.
See the log showing the gva-meta
IEdgeInsights/docker_setup$ docker logs -f ia_visualizer 

2020-08-12 05:53:14,625 : INFO  : Insecure Mode : root : [visualize.py] :callback : in line : [283] : Metadata is : {'channels': 3, 'gva_meta': [{'x': 200, 'height': 18, 'y': 533, 'width': 66, 'tensor': [{'label': '', 'label_id': 2, 'confidence': 0.6547675132751465, 'attribute': 'detection'}, {'label': '<Zhejiang>DJU553', 'label_id': 0, 'confidence': 0, 'attribute': 'license_plate'}]}], 'encoding_type': 'jpeg', 'height': 720, 'img_handle': '14b6e6bd4d', 'width': 1280, 'encoding_level': 96}
//
Is there anyone familiar with the GVA working in EIS ?

**Comment by nnshah1** [comment]
@kqchen 

Is the EIS framework a requirement? Another option at the microservice layer might be:

https://github.com/intel/video-analytics-serving 

I will also forward your question to the teams working more directly on EIS - we are familiar with both projects but I don't have the latest setup and they would probably be able to answer more quickly. I assume its a configuration / dependency / slight adjustment needed - and nothing fundamental.

**Comment by calebmm** [comment]
Hi @kqchen,

The EIS Visualizer is most likely only showing "0" for all labels because the labels information needs to be updated in the same file where you update the GStreamer pipeline: docker_setup/provision/config/etcd_pre_load.json 

However, instead of editing the config in "VideoIngestion/config/" section, you will want to edit the "Visualizer/config" section. By default, it should look like this:

`  "/Visualizer/config": {
      "display": "true",
      "save_image": "false",
      "labels" : {
          "camera1_stream_results": {
              "0": "MISSING",
              "1": "SHORT"
          },
          "camera2_stream_results":{
              "1": "safety_helmet",
              "2": "safety_jacket",
              "3": "Safe",
              "4": "Violation"
          }
      }
  }
`
Since you are running analytics directly in the VideoIngestion container, you will want to add a section for the labels to use for that pub topic. You can see exactly what pub topic your container is using in docker_setup/docker-compose.yml. By default, it is "camera1_stream" for the VideoIngestion container, and "camera1_stream_results" for the VideoAnalytics container.

If you update the labels config section, you should be able to re-provision and launch the EIS containers and see the output on the Visualizer!

**Comment by kqchen** [comment]
Hi @calebmm  :
I did not using your suggestion to add pub topic. I modified the Visualizer/visualizer.py and find out from the the gva-meta for what I needed on the license-plate and made it worked. But I am going to try to add pub topic to see what happened.

**Comment by intel-neena** [comment]
@kqchen Is it okay to close this ticket? Let us know if you need any further help.

**Comment by kqchen** [comment]
yes
